export const dargahShrines = [
  {
    slug: "ajmer-sharif",
    name: "Dargah Khwaja Moinuddin Chishti",
    saint: "Khwaja Moinuddin Chishti (Gharib Nawaz)",
    location: "Ajmer, Rajasthan",
    description: "The sacred dargah of Gharib Nawaz — the protector of the poor. Khwaja Sahib's dargah is visited by millions regardless of faith, and Thursday nights here with qawwali devotional music are among the most spiritually powerful experiences in the subcontinent.",
    theme: "bg-green-50",
    icon: "☪️",
    auspiciousDays: ["Thursdays", "Urs festival (6th Rajab)", "Shab-e-Barat"],
    rituals: [
      { id: "chaddar", name: "Chaddar Offering", price: 35, duration: "1 day", includes: ["Premium chaddar placed at shrine", "Fatiha recited", "Video + photos", "Tabaruk (blessed sweets) shipped"] },
      { id: "qawwali", name: "Qawwali Dedication", price: 25, duration: "1 night", includes: ["Your mannat announced at Thursday qawwali", "Audio/video of dedication", "Blessed rose petals shipped"] },
      { id: "fatiha", name: "Fatiha & Dua", price: 20, duration: "1 day", includes: ["Fatiha recited at the shrine", "Personal dua with your name", "Video proof"] },
      { id: "urs", name: "Urs Festival Special Booking", price: 80, duration: "Urs days", includes: ["Participation in Urs rituals", "Chaddar + flowers", "Full ceremony video", "Blessed items shipped"] },
    ],
  },
  {
    slug: "data-darbar",
    name: "Data Darbar Shrine",
    saint: "Hazrat Ali Hujwiri (Data Ganj Bakhsh)",
    location: "Lahore, Punjab, Pakistan",
    description: "The most revered shrine in Pakistan, Data Ganj Bakhsh — the giver of treasures — has blessed this land for nearly a thousand years. The Thursday night gatherings here are legendary across South Asia.",
    theme: "bg-emerald-50",
    icon: "🌙",
    auspiciousDays: ["Thursdays", "Urs festival", "Shab-e-Qadr"],
    rituals: [
      { id: "chadar", name: "Chadar Offering", price: 30, duration: "1 day", includes: ["Chadar placed at Data Sahib's mazaar", "Fatiha", "Video proof", "Tabaruk shipped"] },
      { id: "mannat", name: "Mannat Dedication", price: 25, duration: "1 day", includes: ["Your specific wish presented at shrine", "Dua on your behalf", "Photo proof"] },
      { id: "thursday-mehfil", name: "Thursday Night Mehfil", price: 20, duration: "1 night", includes: ["Name in Thursday night gathering", "Video of mehfil", "Blessed rose water shipped"] },
    ],
  },
  {
    slug: "nizamuddin",
    name: "Hazrat Nizamuddin Dargah",
    saint: "Hazrat Nizamuddin Auliya",
    location: "New Delhi",
    description: "The dargah of Hazrat Nizamuddin Auliya, the great Chishti saint of Delhi, is one of the most vibrant spiritual spaces in India. The Thursday evening qawwali here has been performed without interruption for 700 years.",
    theme: "bg-teal-50",
    icon: "⭐",
    auspiciousDays: ["Thursdays", "Urs", "Basant Panchami (Basant celebration here)"],
    rituals: [
      { id: "qawwali-dedication", name: "Qawwali Dedication", price: 20, duration: "1 night", includes: ["Name in Thursday qawwali", "Video recording", "Blessed flowers shipped"] },
      { id: "chadar", name: "Chadar & Flowers", price: 25, duration: "1 day", includes: ["Chadar + rose offering", "Fatiha recited", "Photo with your dedication"] },
      { id: "fatiha", name: "Fatiha Khwani", price: 15, duration: "1 day", includes: ["Fatiha recited for your intention", "Video proof", "Blessed tabaruk"] },
    ],
  },
]
