export const hinduTemples = [
  {
    slug: "tirupati",
    name: "Tirumala Venkateswara Temple",
    deity: "Lord Venkateswara (Balaji)",
    location: "Tirupati, Andhra Pradesh",
    description: "One of the world's most visited religious sites, Lord Venkateswara's abode on the seven hills of Tirumala. Devotees believe a darshan here washes away all sins and fulfills heartfelt wishes.",
    theme: "bg-amber-50",
    icon: "🛕",
    auspiciousDays: ["Saturdays", "Ekadashi", "Brahmotsavam period"],
    rituals: [
      { id: "laddu", name: "Laddu Prasad & Archana", price: 15, duration: "1 day", includes: ["Sacred Tirupati laddu shipped", "Archana in your name", "Photo with name board"] },
      { id: "abhishek", name: "Abhishek (Sacred Bath)", price: 45, duration: "1 day", includes: ["Full Abhishek ritual", "Video recording", "Prasad + tilak powder shipped"] },
      { id: "seegra", name: "Seegra Darshan Proxy", price: 80, duration: "1 day", includes: ["Priority darshan on your behalf", "Live video call during darshan", "Blessed items shipped"] },
      { id: "archana", name: "Special Sahasranama Archana", price: 30, duration: "1 day", includes: ["1008 names chanting", "Your family names included", "Video proof"] },
    ],
  },
  {
    slug: "shirdi",
    name: "Shri Sai Baba Mandir",
    deity: "Sai Baba of Shirdi",
    location: "Shirdi, Maharashtra",
    description: "The sacred samadhi of Sai Baba, the saint who embodied 'Sabka Malik Ek' — one God for all. Thursdays here carry special divine energy for wish fulfillment.",
    theme: "bg-orange-50",
    icon: "✨",
    auspiciousDays: ["Thursdays", "Ram Navami", "Guru Purnima"],
    rituals: [
      { id: "thursday-aarti", name: "Thursday Kakad Aarti Dedication", price: 20, duration: "1 day", includes: ["Name announced at morning aarti", "Aarti video shared", "Udi (sacred ash) shipped"] },
      { id: "abhishek", name: "Panchamrit Abhishek", price: 35, duration: "1 day", includes: ["Full Abhishek with panchamrit", "Video recording", "Prasad shipped"] },
      { id: "palki", name: "Palki Procession Dedication", price: 25, duration: "1 day", includes: ["Name included in evening palki", "Video of procession", "Blessed Udi"] },
    ],
  },
  {
    slug: "kedarnath",
    name: "Kedarnath Jyotirlinga",
    deity: "Lord Shiva (Mahadev)",
    location: "Kedarnath, Uttarakhand (3,583m altitude)",
    description: "One of the 12 Jyotirlingas, nestled in the Himalayas at 3,583 meters. This ancient stone temple is believed to have been built by the Pandavas. Prayers here are said to be heard directly by Mahadev.",
    theme: "bg-slate-50",
    icon: "⛰️",
    auspiciousDays: ["Mondays", "Shravan month", "Mahashivratri", "Temple opening day"],
    rituals: [
      { id: "rudrabhishek", name: "Rudrabhishek", price: 60, duration: "1 day", includes: ["Rudrabhishek with Gangajal", "Bilva patra offering", "Video + photos", "Vibhuti shipped"] },
      { id: "laghu-rudra", name: "Laghu Rudra", price: 120, duration: "1 day", includes: ["Laghu Rudra path", "11 pandits chanting", "Full video", "Prasad shipped"] },
      { id: "bhasma-aarti", name: "Morning Aarti Dedication", price: 40, duration: "1 day", includes: ["Name at morning aarti", "Aarti video", "Himalayan rudraksha shipped"] },
    ],
  },
  {
    slug: "vaishno-devi",
    name: "Vaishno Devi Shrine",
    deity: "Mata Vaishno Devi",
    location: "Trikuta Mountains, Jammu & Kashmir",
    description: "Mata Vaishno Devi's cave shrine in the Trikuta Mountains is one of the most visited pilgrimage sites in India. Mata is said to grant boons to all who call upon her with a pure heart.",
    theme: "bg-red-50",
    icon: "🏔️",
    auspiciousDays: ["Navratri", "Ashtami", "Purnima"],
    rituals: [
      { id: "darshan-proxy", name: "Darshan Proxy Visit", price: 50, duration: "2 days", includes: ["Full trek + cave darshan", "Live video during darshan", "Chunri & prasad shipped"] },
      { id: "chunri", name: "Chunri Chadhana", price: 30, duration: "1 day", includes: ["Red chunri offered in your name", "Photo with your name", "Blessed vermilion shipped"] },
      { id: "special-puja", name: "Navratri Special Puja", price: 90, duration: "1 day", includes: ["Navratri-specific rituals", "Video call option", "Full prasad kit shipped"] },
    ],
  },
  {
    slug: "mahakaleshwar",
    name: "Mahakaleshwar Jyotirlinga",
    deity: "Mahakal (Lord Shiva)",
    location: "Ujjain, Madhya Pradesh",
    description: "The only Jyotirlinga facing south (Dakshinamukhi), Mahakaleshwar is the lord of time itself. The legendary Bhasma Aarti performed at 4 AM with sacred ash is witnessed by thousands who believe it removes fear of death.",
    theme: "bg-zinc-50",
    icon: "🔱",
    auspiciousDays: ["Mondays", "Mahashivratri", "Shravan Mondays"],
    rituals: [
      { id: "bhasma-aarti", name: "4AM Bhasma Aarti Dedication", price: 55, duration: "1 day", includes: ["Name at the legendary Bhasma Aarti", "Full video of rare ritual", "Sacred bhasma (ash) shipped"] },
      { id: "rudrabhishek", name: "Rudrabhishek", price: 70, duration: "1 day", includes: ["Rudrabhishek with 5 sacred items", "Video", "Prasad + rudraksha"] },
      { id: "naivedya", name: "Naivedya Offering", price: 25, duration: "1 day", includes: ["Food offering in your name", "Photo proof", "Blessed tilak powder"] },
    ],
  },
]
