export type RitualFee = { name: string; amount: number }

export type Ritual = {
  id: string
  name: string
  description: string
  offerings: string
  duration: string
  price: number
  fees?: RitualFee[]  // optional fee breakdown
  includes: string[]
  livestream: boolean
  source: string // price source — not shown on UI
}

export type Place = {
  slug: string
  id: string
  name: string
  type: "temple" | "gurdwara" | "dargah" | "church" | "monastery" | "ashram" | "samadhi" | "shrine" | "mosque"
  location: { city: string; state: string; country: string }
  primaryFigure: string
  faith: string
  icon: string
  theme: { bg: string; nav: string; navText: string; accent: string; accentText: string; badge: string; badgeText: string }
  description: string
  significance: string
  auspiciousDays: string[]
  rituals: Ritual[]
  festivals: string[]
  diaspora: string[]
  lifeProblems: string[]
  trustNotes: string | null
  tags: string[]
}

export const places: Place[] = [
  // ── HINDU TEMPLES ──────────────────────────────────────────────────────────
  {
    slug: "kashi-vishwanath",
    id: "H001",
    name: "Kashi Vishwanath Temple",
    type: "temple",
    location: { city: "Varanasi", state: "Uttar Pradesh", country: "India" },
    primaryFigure: "Lord Shiva (Vishwanath)",
    faith: "Hindu — Shaivism",
    icon: "🔱",
    theme: { bg: "bg-orange-50", nav: "bg-orange-800", navText: "text-white", accent: "bg-orange-600", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-800" },
    description: "One of the twelve Jyotirlingas and the most sacred temple of Lord Shiva, situated on the banks of the Ganges in Varanasi — the city of liberation. A darshan here is believed to grant moksha.",
    significance: "Dying in Varanasi is said to guarantee liberation, as Shiva himself whispers the Taraka mantra into the dying person's ear.",
    auspiciousDays: ["Mondays", "Mahashivratri", "Shravan month", "Pradosh"],
    rituals: [
      {
        id: "rudrabhishek-vc",
        name: "Rudrabhishek (Video Conference)",
        description: "Sacred ablution of the Shiva Linga by 1 temple Shastri — you receive a live video link; priest performs in your name with your sankalpa",
        offerings: "Water, milk, honey, ghee, Bilva leaves, flowers",
        duration: "45–90 minutes",
        price: 18,
        fees: [
          { name: "Sacred Offerings Procurement", amount: 4 },
          { name: "Priest Coordination & Sankalpa Setup", amount: 3 },
          { name: "Digital Delivery Package", amount: 3 },
        ],
        includes: ["Full Rudrabhishek with 11 sacred items", "Sankalpa with your name & gotra", "Live WhatsApp video link", "Vibhuti (sacred ash) shipped by post"],
        livestream: true,
        source: "Official KV Puja List — Rudrabhishek (Video Conference, 1 Shastri): ₹700 plus service fee. shrikashivishwanath.org/frontend/home/poojaList"
      },
      {
        id: "rudrabhishek-vc-5shastri",
        name: "Rudrabhishek (Video Conference, 5 Shastri)",
        description: "Extended Rudrabhishek with five temple shastris performing the sacred abhishek in your name via live video link",
        offerings: "Water, milk, honey, ghee, Bilva leaves, flowers",
        duration: "90–120 minutes",
        price: 25,
        fees: [
          { name: "Multi-Priest Coordination Fee", amount: 4 },
          { name: "Sacred Offerings Procurement", amount: 3 },
          { name: "Digital Delivery Package", amount: 2 },
        ],
        includes: ["Five Shastri priests perform the Rudrabhishek", "Sankalpa with your name & gotra", "Live WhatsApp video link", "Vibhuti and Gangajal shipped"],
        livestream: true,
        source: "Official KV Puja List — Rudrabhishek (Video Conference, 5 Shastri): ₹2,100 plus service fee. shrikashivishwanath.org/frontend/home/poojaList"
      },
      {
        id: "mangala-aarti",
        name: "Mangala Aarti Pass (3 AM)",
        description: "Pre-dawn lamp ceremony — our officiant uses a booked pass and announces your name at the most auspicious aarti of the day",
        offerings: "Incense, flowers, lamps",
        duration: "15–20 minutes",
        price: 9,
        fees: [
          { name: "Auspicious Timeslot Reservation", amount: 5 },
          { name: "Priest Coordination & Booking", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Name announced at 3 AM Mangala Aarti", "Video of the ceremony sent within 6 hours", "Gangajal + prasad shipped"],
        livestream: true,
        source: "Official KV Mangala Aarti pass: ₹500 plus service fee. shrikashivishwanath.org"
      },
      {
        id: "shringar-aarti",
        name: "Shringar / Bhog Aarti",
        description: "Evening decoration and lamp-waving ceremony — your name offered at this popular evening seva",
        offerings: "Flowers, lamps",
        duration: "20 minutes",
        price: 7,
        fees: [
          { name: "Auspicious Timeslot Reservation", amount: 5 },
          { name: "Priest Coordination Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 4 },
        ],
        includes: ["Name at Shringar Aarti", "Video proof", "Tilak powder shipped"],
        livestream: false,
        source: "Official KV Shringar/Bhog Aarti pass: ₹300 plus service fee. shrikashivishwanath.org"
      },
      {
        id: "pind-daan",
        name: "Pind Daan (Ancestor Rites at Ganga Ghat)",
        description: "Sacred rice-ball offerings for the liberation of ancestors, performed by an authorized panda at Assi Ghat on the Ganges",
        offerings: "Rice balls (pinda), sesame, Gangajal, flowers",
        duration: "1.5–2 hours",
        price: 48,
        fees: [
          { name: "Sacred Offerings Procurement", amount: 3 },
          { name: "Authorized Panda Coordination", amount: 3 },
          { name: "Digital Documentation Package", amount: 2 },
        ],
        includes: ["Full Pind Daan on Ganga ghat by authorized panda", "All ancestors' names chanted", "Video recording", "Gangajal shipped"],
        livestream: false,
        source: "Ghat panda authorized rate for full Pind Daan with materials: ₹2,500–₹3,500. SacredReach service fee added for authorized panda coordination and documentation."
      },
    ],
    festivals: ["Maha Shivaratri", "Shravan Mondays", "Dev Deepawali", "Diwali"],
    diaspora: ["USA", "UK", "Canada", "Mauritius"],
    lifeProblems: ["Ancestor liberation", "Sin removal", "Moksha", "Health", "Prosperity"],
    trustNotes: "Managed by Shri Kashi Vishwanath Temple Trust (Varanasi Nagar Nigam)",
    tags: ["shiva", "jyotirlinga", "varanasi", "moksha", "ancestor-rites"],
  },
  {
    slug: "tirupati-balaji",
    id: "H002",
    name: "Tirumala Venkateswara Temple",
    type: "temple",
    location: { city: "Tirupati", state: "Andhra Pradesh", country: "India" },
    primaryFigure: "Lord Venkateswara (Balaji)",
    faith: "Hindu — Vaishnavism",
    icon: "🛕",
    theme: { bg: "bg-yellow-50", nav: "bg-yellow-700", navText: "text-white", accent: "bg-yellow-600", accentText: "text-white", badge: "bg-yellow-100", badgeText: "text-yellow-800" },
    description: "The world's most visited religious site, Lord Venkateswara's abode on the seven sacred hills of Tirumala. It is said that any sincere prayer made here is always answered.",
    significance: "Devotees believe Balaji fulfills any wish made with genuine devotion. The tonsuring (head-shaving) here is one of the most common fulfillment rituals in the world.",
    auspiciousDays: ["Saturdays", "Ekadashi", "Brahmotsavam", "Vaikunta Ekadashi"],
    rituals: [
      {
        id: "archana",
        name: "Archana (Nityotsavam)",
        description: "Daily archana in your name and family names presented to Lord Venkateswara — the most accessible TTD seva",
        offerings: "Tulsi, flowers",
        duration: "Included in daily seva cycle",
        price: 29,
        fees: [
          { name: "TTD Quota Booking Fee", amount: 4 },
          { name: "International Prasad Packaging & Dispatch", amount: 5 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Archana with your name + 1 family name", "Digital photo of TTD receipt shared", "2 Tirupati laddus shipped internationally"],
        livestream: false,
        source: "TTD Archana (Nityotsavam): ₹220 plus service fee and shipping. arjithaseva.tirupatibalaji.ap.gov.in — booked via TTD quota system."
      },
      {
        id: "kalyanotsavam",
        name: "Kalyanotsavam (Celestial Wedding)",
        description: "The daily celestial wedding ceremony of Lord Venkateswara and Sri Devi — performed in your family's name via TTD quota booking",
        offerings: "Flowers, silk, sweets",
        duration: "1 seva session (~30 min)",
        price: 38,
        fees: [
          { name: "TTD Quota Booking Fee", amount: 4 },
          { name: "International Prasad Packaging & Dispatch", amount: 4 },
          { name: "Agent Coordination Fee", amount: 3 },
        ],
        includes: ["Kalyanotsavam in your family's name", "Official TTD ticket receipt shared", "Prasad + tilak powder shipped"],
        livestream: false,
        source: "TTD Kalyanotsavam: ₹1,000 plus agent coordination fee. Booked via official TTD arjitha seva quota. ttdevasthanams.ap.gov.in"
      },
      {
        id: "sahasra-deepalankarana",
        name: "Sahasra Deepalankarana Seva",
        description: "Lord decorated with 1,000 lamps — one of Tirupati's most visually spectacular daily sevas",
        offerings: "1,000 oil lamps, flowers",
        duration: "1 seva session",
        price: 12,
        fees: [
          { name: "TTD Quota Booking Fee", amount: 5 },
          { name: "Prasad Packaging & International Dispatch", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Seva in your name via TTD quota", "Video/photo of the lamp ceremony", "Prasad shipped"],
        livestream: false,
        source: "TTD Sahasra Deepalankarana Seva: ₹200 plus service fee. ttdevasthanams.ap.gov.in"
      },
      {
        id: "sahasranama-archana",
        name: "Sahasranama Archana (1008 Names)",
        description: "Chanting of all 1008 divine names of Lord Venkateswara — arranged through a TTD-approved temple pujari",
        offerings: "1 flower per name",
        duration: "2 hours",
        price: 24,
        fees: [
          { name: "Vedic Pujari Network Coordination", amount: 5 },
          { name: "International Prasad Packaging & Dispatch", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["1008 names chanted with your name and family", "Video clip of chanting", "Prasad + tulsi mala shipped"],
        livestream: false,
        source: "TTD-approved pujari arrangement at Tirumala for Sahasranama Archana: ₹1,100–₹1,500 plus service fee. Not in the public arjitha seva catalog; arranged via authorized Vedic pujari network."
      },
    ],
    festivals: ["Brahmotsavam (9 days)", "Vaikunta Ekadashi", "Ugadi"],
    diaspora: ["USA", "UK", "Canada", "Malaysia", "Singapore", "Australia"],
    lifeProblems: ["Wish fulfillment", "Marriage", "Children", "Career", "Devotion"],
    trustNotes: "Managed by Tirumala Tirupati Devasthanams (TTD) — Andhra Pradesh government body",
    tags: ["vishnu", "balaji", "venkateswara", "andhra", "wish-fulfillment"],
  },
  {
    slug: "shirdi-sai-baba",
    id: "H003",
    name: "Shri Sai Baba Mandir",
    type: "temple",
    location: { city: "Shirdi", state: "Maharashtra", country: "India" },
    primaryFigure: "Sai Baba of Shirdi",
    faith: "Universal — Hindu & Muslim devotees both",
    icon: "✨",
    theme: { bg: "bg-amber-50", nav: "bg-amber-700", navText: "text-white", accent: "bg-amber-600", accentText: "text-white", badge: "bg-amber-100", badgeText: "text-amber-800" },
    description: "The samadhi shrine of Sai Baba of Shirdi, who embodied 'Sabka Malik Ek' — one God for all. He transcended all religion and is worshipped by Hindus, Muslims, and people of every faith.",
    significance: "Sai Baba promised: 'If you look to me, I look to you.' Thursdays here are considered the most powerful day for wish fulfillment.",
    auspiciousDays: ["Thursdays", "Ram Navami", "Guru Purnima", "Vijayadashami"],
    rituals: [
      {
        id: "kakad-aarti",
        name: "Kakad Aarti Pass (5:30 AM)",
        description: "Pre-dawn aarti on Baba's most auspicious morning — an official pass is booked and your name offered",
        offerings: "Flowers, incense",
        duration: "30 minutes",
        price: 9,
        fees: [
          { name: "Official Pass Procurement & Facilitation", amount: 5 },
          { name: "Auspicious Timeslot Reservation", amount: 4 },
          { name: "Udi Packaging & International Dispatch", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Official Shirdi Sansthan Kakad Aarti pass booked in your name", "Video of the aarti ceremony", "Udi (sacred ash) shipped by post"],
        livestream: true,
        source: "Shirdi Sai Sansthan official Kakad Aarti pass: ₹500–₹600. online.sai.org.in — bookable up to 60 days in advance."
      },
      {
        id: "abhishek",
        name: "Panchamrit Abhishek (Sansthan-Linked Pujari)",
        description: "Sacred bathing of Sai Baba's samadhi arranged through a Sansthan-authorized priest",
        offerings: "Milk, rose water, curd, honey, sugar",
        duration: "1 abhishek session",
        price: 17,
        fees: [
          { name: "Sansthan-Authorized Pujari Coordination", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & International Dispatch", amount: 4 },
          { name: "Platform Service Fee", amount: 2 },
        ],
        includes: ["Full abhishek video from the samadhi mandir", "Prasad from the Sansthan kitchen shipped", "Name board photo"],
        livestream: false,
        source: "Shirdi Sai Sansthan authorized pujari rate for Panchamrit Abhishek: ₹1,100–₹1,500. Arranged via Sansthan-linked karyakarta network. sai.org.in"
      },
      {
        id: "palki",
        name: "Palki Procession Evening Dedication",
        description: "Your name offered during the evening palki (palanquin) procession at the samadhi mandir",
        offerings: "Rose petals, incense",
        duration: "1 hour",
        price: 12,
        fees: [
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Udi & Prasad Packaging & Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Name in the evening palki procession", "Video of the procession", "Udi + prasad shipped"],
        livestream: false,
        source: "Evening palki is a free event at Shirdi Sai Sansthan; our representative attends and makes dedication. Arrangement fee: ₹500–₹800."
      },
    ],
    festivals: ["Guru Purnima", "Ram Navami", "Diwali at Shirdi"],
    diaspora: ["USA", "UK", "Canada", "UAE", "Australia", "New Zealand"],
    lifeProblems: ["Wish fulfillment", "Faith", "Health", "Obstacles", "Family peace"],
    trustNotes: "Managed by Shri Saibaba Sansthan Trust, Shirdi",
    tags: ["sai-baba", "shirdi", "universal", "guru", "thursday"],
  },
  {
    slug: "kedarnath",
    id: "H004",
    name: "Kedarnath Jyotirlinga",
    type: "temple",
    location: { city: "Kedarnath", state: "Uttarakhand", country: "India" },
    primaryFigure: "Lord Shiva (Kedarnath)",
    faith: "Hindu — Shaivism",
    icon: "⛰️",
    theme: { bg: "bg-slate-50", nav: "bg-slate-800", navText: "text-white", accent: "bg-slate-700", accentText: "text-white", badge: "bg-slate-100", badgeText: "text-slate-800" },
    description: "Perched at 3,583 metres in the Himalayas, Kedarnath is one of the 12 Jyotirlingas and part of the sacred Char Dham. Open only 6 months a year (May–November).",
    significance: "Legend says the Pandavas sought forgiveness here after the Mahabharata war. A darshan of Kedarnath cleanses all sins of this life and the next.",
    auspiciousDays: ["Mondays", "Shravan month", "Mahashivratri", "Temple opening day (May)"],
    rituals: [
      {
        id: "shiv-sahasranaam",
        name: "Shiv Sahasranaam Path",
        description: "1000 names of Shiva recited at the ancient temple by BKTC priests — bookable online, no attendance required",
        offerings: "Flowers, incense, bilva",
        duration: "1 hour",
        price: 18,
        fees: [
          { name: "BKTC Booking Coordination", amount: 4 },
          { name: "High-Altitude Logistics Fee", amount: 5 },
          { name: "Registered Post Prasad Dispatch", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Full Sahasranaam recitation at Kedarnath", "Video recording", "Atka Bhog prasad shipped via registered post"],
        livestream: false,
        source: "BKTC (Badrinath-Kedarnath Temple Committee) Shiv Sahasranaam Path: ₹2,000 plus service fee. Official online booking: badrinath-kedarnath.gov.in/online-services/book-puja-online/"
      },
      {
        id: "rudrabhishek",
        name: "Rudrabhishek (Priest-Performed, Non-Attending)",
        description: "Sacred ablution with Gangajal and bilva at the ancient linga — our BKTC-linked priest performs; prasad shipped via registered post",
        offerings: "Gangajal, milk, bilva, flowers",
        duration: "45–60 minutes",
        price: 52,
        fees: [
          { name: "BKTC Arrangement Fee", amount: 4 },
          { name: "High-Altitude Logistics Fee", amount: 3 },
          { name: "Digital Documentation Package", amount: 2 },
        ],
        includes: ["Rudrabhishek at Kedarnath by temple priest", "Video + photos", "Atka Bhog prasad (registered post, ₹980)"],
        livestream: false,
        source: "BKTC non-attending puja arrangement. Atka Bhog (prasad) registered post: ₹1,270. Priest-arranged Rudrabhishek without attendance: ₹1,500–₹2,100 plus service fee. badrinath-kedarnath.gov.in"
      },
      {
        id: "morning-aarti",
        name: "Morning Aarti Dedication",
        description: "Your name offered at Kedarnath's morning aarti — Kapoor Aarti or Chandi Aarti booked via BKTC",
        offerings: "Incense, camphor, flowers, bilva",
        duration: "30 minutes",
        price: 18,
        fees: [
          { name: "BKTC Booking Coordination", amount: 4 },
          { name: "High-Altitude Logistics Fee", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Himalayan Rudraksha Packaging & Dispatch", amount: 4 },
        ],
        includes: ["Name at morning aarti (Kapoor/Chandi Aarti)", "Aarti video", "Himalayan rudraksha shipped"],
        livestream: false,
        source: "BKTC Kapoor Aarti: ₹201; Chandi Aarti: ₹401 plus service fee for representative booking and documentation. badrinath-kedarnath.gov.in/online-services/book-puja-online/"
      },
    ],
    festivals: ["Kedarnath Dham opening (May)", "Mahashivratri", "Shravan Mondays"],
    diaspora: ["USA", "UK", "Canada", "UAE"],
    lifeProblems: ["Sin removal", "Moksha", "Health", "Courage", "Spiritual elevation"],
    trustNotes: "Managed by Shri Badrinath-Kedarnath Temple Committee (BKTC), Uttarakhand government",
    tags: ["shiva", "jyotirlinga", "char-dham", "himalayas", "kedarnath"],
  },
  {
    slug: "vaishno-devi",
    id: "H005",
    name: "Vaishno Devi Shrine",
    type: "shrine",
    location: { city: "Katra", state: "Jammu & Kashmir", country: "India" },
    primaryFigure: "Mata Vaishno Devi (Shakti)",
    faith: "Hindu — Shaktism",
    icon: "🏔️",
    theme: { bg: "bg-red-50", nav: "bg-red-800", navText: "text-white", accent: "bg-red-700", accentText: "text-white", badge: "bg-red-100", badgeText: "text-red-800" },
    description: "Mata Vaishno Devi's cave shrine in the Trikuta Mountains is one of the most visited pilgrimage sites in India. The 14-km trek to the cave shrine is itself considered a form of devotion.",
    significance: "Mata is believed to call devotees when the time is right. 'Jai Mata Di' is the cry of those who have felt her call.",
    auspiciousDays: ["Navratri (twice a year)", "Ashtami", "Purnima", "Saturdays"],
    rituals: [
      {
        id: "hawan-remote",
        name: "Official Hawan Puja (No Trek Required)",
        description: "The Shrine Board's own Hawan service — registered officially via maavaishnodevi.org, priests perform at the shrine without devotee's physical presence",
        offerings: "Full hawan samagri (supplied by Shrine Board)",
        duration: "1 hawan session",
        price: 28,
        fees: [
          { name: "Shrine Board Registration Facilitation", amount: 4 },
          { name: "Sacred Materials Procurement", amount: 3 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Prasad Packaging & International Dispatch", amount: 4 },
        ],
        includes: ["Official Shrine Board Hawan registration (₹2,100)", "Video of the hawan", "Prasad + vermilion shipped"],
        livestream: false,
        source: "Vaishno Devi Shrine Board official Hawan Puja: ₹2,100. online.maavaishnodevi.org — the Board explicitly warns against third-party agents."
      },
      {
        id: "chunri-proxy",
        name: "Chunri Chadhana (Full Proxy Trek)",
        description: "Our vetted trekker completes the 14-km trek and places your red chunri at Mata's cave shrine (pindies darshan)",
        offerings: "Red chunri, coconut, flowers",
        duration: "2-day trek",
        price: 65,
        fees: [
          { name: "Trekker Documentation & Coordination", amount: 4 },
          { name: "Shrine Board Permit Facilitation", amount: 3 },
          { name: "Digital Documentation Package", amount: 2 },
        ],
        includes: ["Full 14-km trek + cave darshan by our representative", "Chunri placed at pindies in your name", "Video during darshan", "Blessed vermilion + prasad shipped"],
        livestream: false,
        source: "Shrine Board permits authorized guide hire. Trekker + chunri materials: ₹3,000–₹5,000. Guide registration via maavaishnodevi.org."
      },
      {
        id: "navratri-puja",
        name: "Navratri Special Hawan",
        description: "Elaborate special Hawan during the sacred nine nights — Shrine Board surcharge applies during Navratri",
        offerings: "Full puja samagri, hawan kund",
        duration: "1 hawan session",
        price: 55,
        fees: [
          { name: "Peak-Season Coordination Surcharge", amount: 4 },
          { name: "Sacred Materials Procurement", amount: 3 },
          { name: "Digital Documentation Package", amount: 2 },
        ],
        includes: ["Navratri special Hawan at shrine premises", "Video", "Full prasad kit (vermilion, chunri, prasad) shipped"],
        livestream: false,
        source: "Shrine Board Navratri Hawan: ₹2,100 base + peak-season surcharge. online.maavaishnodevi.org — Navratri surcharge can add ₹21,000+ for SSVP puja; Hawan remains standard."
      },
    ],
    festivals: ["Navratri (spring & autumn)", "Diwali"],
    diaspora: ["USA", "UK", "Canada", "UAE", "Australia"],
    lifeProblems: ["Wish fulfillment", "Protection", "Fertility", "Marriage", "Recovery"],
    trustNotes: "Managed by Shri Mata Vaishno Devi Shrine Board (J&K government)",
    tags: ["shakti", "mata", "devi", "navratri", "cave-shrine"],
  },
  {
    slug: "mahakaleshwar",
    id: "H006",
    name: "Mahakaleshwar Jyotirlinga",
    type: "temple",
    location: { city: "Ujjain", state: "Madhya Pradesh", country: "India" },
    primaryFigure: "Mahakal (Lord Shiva)",
    faith: "Hindu — Shaivism",
    icon: "🔱",
    theme: { bg: "bg-zinc-50", nav: "bg-zinc-800", navText: "text-white", accent: "bg-zinc-700", accentText: "text-white", badge: "bg-zinc-100", badgeText: "text-zinc-800" },
    description: "The only south-facing (Dakshinamukhi) Jyotirlinga. The legendary Bhasma Aarti at 4 AM — where the deity is anointed with cremation ash — is one of the rarest rituals in Hindu worship.",
    significance: "Worshipping Mahakal frees devotees from the fear of death and the cycle of time itself.",
    auspiciousDays: ["Mondays", "Mahashivratri", "Shravan Mondays", "Kumbh Mela"],
    rituals: [
      {
        id: "bhasma-aarti",
        name: "Bhasma Aarti Pass (4 AM — Online Booking)",
        description: "Online pass booked for the unique 4 AM Bhasma Aarti — our officiant attends; deity anointed with fresh cremation ash from Manikarnika Ghat",
        offerings: "Sacred bhasma (fresh cremation ash)",
        duration: "1 hour",
        price: 6,
        fees: [
          { name: "Online Pass Procurement & Facilitation", amount: 5 },
          { name: "Auspicious Timeslot Reservation", amount: 5 },
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 5 },
          { name: "Sacred Bhasma Packaging & Dispatch", amount: 5 },
        ],
        includes: ["Online pass booked (₹200)", "Full aarti video sent within 6 hours", "Sacred bhasma (ash) shipped"],
        livestream: false,
        source: "Mahakaleshwar official Bhasma Aarti online pass: ₹200. mahakaleshwar.nic.in — passes open 30 days in advance; highly competitive."
      },
      {
        id: "rudrabhishek",
        name: "Rudrabhishek (11 Avartan — Full)",
        description: "Full Rudrabhishek with 11 complete recitations of Shri Rudram at the Dakshinamukhi Shiva linga",
        offerings: "Milk, honey, ghee, bilva, Gangajal",
        duration: "2 hours",
        price: 14,
        fees: [
          { name: "Sacred Offerings Procurement", amount: 5 },
          { name: "Priest Coordination & Booking", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Rudraksha & Prasad Packaging & Dispatch", amount: 4 },
        ],
        includes: ["Full 11-avartan Rudrabhishek at Mahakaleshwar", "Video", "Prasad + rudraksha shipped"],
        livestream: false,
        source: "Mahakaleshwar Temple Rudrabhishek (11 Avartan): ₹1,000. shrimahakaleshwar.com / shrimahakaleshwar.mp.gov.in"
      },
      {
        id: "naivedya",
        name: "Naivedya (Food Offering + Archana)",
        description: "Food and flower offering to Mahakal with basic archana in your name",
        offerings: "Sweets, fruits, flowers, incense",
        duration: "30 minutes",
        price: 5,
        fees: [
          { name: "Sacred Offerings Procurement", amount: 5 },
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Priest Coordination Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 5 },
          { name: "Blessed Tilak & Prasad Packaging & Dispatch", amount: 5 },
        ],
        includes: ["Offering in your name", "Photo proof", "Blessed tilak + prasad shipped"],
        livestream: false,
        source: "Mahakaleshwar General Archana: ₹100; Rudrabhishek (1 Avartan): ₹300. shrimahakaleshwar.com"
      },
    ],
    festivals: ["Mahashivratri", "Shravan Mondays", "Kumbh Mela (every 12 years)"],
    diaspora: ["USA", "UK", "Canada"],
    lifeProblems: ["Fear of death", "Time/destiny", "Enemies", "Spiritual power"],
    trustNotes: "Managed by Mahakaleshwar Temple Committee (MP government)",
    tags: ["shiva", "jyotirlinga", "ujjain", "bhasma-aarti", "dakshinamukhi"],
  },
  {
    slug: "jagannath-puri",
    id: "H007",
    name: "Jagannath Temple, Puri",
    type: "temple",
    location: { city: "Puri", state: "Odisha", country: "India" },
    primaryFigure: "Lord Jagannath (Vishnu)",
    faith: "Hindu — Vaishnavism",
    icon: "🎪",
    theme: { bg: "bg-orange-50", nav: "bg-orange-700", navText: "text-white", accent: "bg-orange-600", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-800" },
    description: "Lord Jagannath — Lord of the Universe — presides at Puri, one of India's four sacred dhams. The annual Rath Yatra draws millions. The Mahaprasad (temple food) has no caste distinction.",
    significance: "The Mahaprasad is considered so sacred that even Brahma is said to desire it. There is no caste distinction in Jagannath's kitchen — all are equal here.",
    auspiciousDays: ["Rath Yatra", "Ekadashi", "Purnima", "Snana Purnima"],
    rituals: [
      {
        id: "mahaprasad",
        name: "Mahaprasad via Authorized Sevayet",
        description: "Chhappan Bhog (56-variety) food offering arranged through an authorized hereditary sevayet (servitor) — the temple itself does not accept online booking for pujas",
        offerings: "56 varieties of food (Chhappan Bhog)",
        duration: "1 day",
        price: 28,
        fees: [
          { name: "Authorized Sevayet Coordination", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Mahaprasad Packaging & Dispatch", amount: 4 },
        ],
        includes: ["Chhappan Bhog offered via authorized panda/sevayet", "Photo from inside Ananda Bazaar", "Mahaprasad packed and shipped"],
        livestream: false,
        source: "Jagannath Temple Administration explicitly states no online donation accepted for pujas (shreejagannatha.in). Must use authorized sevayet system. Mahaprasad plate: ₹100–₹200 at Ananda Bazaar. Full sevayet arrangement: ₹2,000–₹2,500."
      },
      {
        id: "aarti-dedication",
        name: "Sandhya Aarti via Authorized Sevayet",
        description: "Evening aarti at the 12th-century temple — dedicated through a registered hereditary servitor (sevayet)",
        offerings: "Lamps, flowers",
        duration: "30 minutes",
        price: 22,
        fees: [
          { name: "Authorized Sevayet Coordination", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Prasad Packaging & International Dispatch", amount: 3 },
        ],
        includes: ["Aarti dedication through registered sevayet", "Video recording", "Tilak + prasad shipped"],
        livestream: false,
        source: "Authorized sevayet arrangement at Jagannath Puri. Temple forbids online puja payment — sevayet system is the only valid remote method. shreejagannatha.in"
      },
    ],
    festivals: ["Rath Yatra (June/July)", "Snana Purnima", "Diwali"],
    diaspora: ["USA", "UK", "Odia diaspora globally"],
    lifeProblems: ["Devotion", "Ancestor blessings", "Liberation", "Equality"],
    trustNotes: "Administered by Sri Jagannath Temple Administration (Odisha government)",
    tags: ["vishnu", "jagannath", "rath-yatra", "char-dham", "puri"],
  },
  {
    slug: "badrinath",
    id: "H008",
    name: "Shri Badrinath Temple",
    type: "temple",
    location: { city: "Badrinath", state: "Uttarakhand", country: "India" },
    primaryFigure: "Vishnu (Badrinarayan)",
    faith: "Hindu — Vaishnavism",
    icon: "🏔️",
    theme: { bg: "bg-blue-50", nav: "bg-blue-800", navText: "text-white", accent: "bg-blue-700", accentText: "text-white", badge: "bg-blue-100", badgeText: "text-blue-800" },
    description: "The most important of the four Char Dham pilgrimage sites, Badrinath sits at 3,133 metres in the Garhwal Himalayas. Open only May–November each year.",
    significance: "'He who chants the name of Badri shall be liberated' — Skanda Purana. One of Adi Shankaracharya's most sacred establishments.",
    auspiciousDays: ["Temple opening day (May)", "Ekadashi", "Makar Sankranti"],
    rituals: [
      {
        id: "vishnusahasranam",
        name: "Vishnusahasranama Path",
        description: "1000 names of Vishnu chanted before Badrinarayan — bookable via BKTC official portal",
        offerings: "Tulsi, flowers",
        duration: "1 hour",
        price: 10,
        fees: [
          { name: "BKTC Booking Coordination", amount: 5 },
          { name: "High-Altitude Logistics Fee", amount: 5 },
          { name: "Prasad Packaging & International Dispatch", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Full Vishnusahasranama recitation in your name", "Video", "Char Dham prasad + tilak shipped"],
        livestream: false,
        source: "BKTC Vishnusahasranam Path: ₹701. badrinath-kedarnath.gov.in/online-services/book-puja-online/"
      },
      {
        id: "swaran-aarti",
        name: "Swaran Aarti Dedication",
        description: "Golden lamp evening ceremony at Badrinath — your name entered via BKTC official aarti booking",
        offerings: "Ghee lamp",
        duration: "20 minutes",
        price: 7,
        fees: [
          { name: "BKTC Booking Coordination", amount: 5 },
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 5 },
          { name: "Prasad Packaging & Dispatch", amount: 4 },
          { name: "Platform Service Fee", amount: 4 },
        ],
        includes: ["Name at Swaran Aarti (BKTC booking ₹501)", "Video", "Prasad sent"],
        livestream: false,
        source: "BKTC Swaran Aarti: ₹501. badrinath-kedarnath.gov.in/online-services/book-puja-online/"
      },
      {
        id: "abhishek",
        name: "Brahma Abhishek (Non-Attending)",
        description: "Early morning abhishek of Badrinarayan with Tapt Kund (natural hot spring) water — BKTC official seva, priests perform on your behalf",
        offerings: "Tapt Kund water, yogurt, Tulsi, flowers",
        duration: "30 minutes",
        price: 57,
        fees: [
          { name: "BKTC Booking Coordination", amount: 4 },
          { name: "Registered Prasad Post Facilitation", amount: 3 },
          { name: "Digital Documentation Package", amount: 2 },
        ],
        includes: ["Abhishek at Badrinath via BKTC official booking (₹4,500)", "Video", "Atka Bhog prasad shipped by registered post"],
        livestream: false,
        source: "BKTC Abhishek Puja (attending, 4:30–6:30 AM): ₹4,500. Non-attending arrangements possible via BKTC-linked priest. badrinath-kedarnath.gov.in"
      },
    ],
    festivals: ["Char Dham Yatra season (May–Nov)", "Badri Kedar Festival"],
    diaspora: ["USA", "UK", "Canada", "Nepal"],
    lifeProblems: ["Spiritual merit", "Pilgrimage fulfillment", "Moksha"],
    trustNotes: "Managed by Shri Badrinath-Kedarnath Temple Committee (BKTC), Uttarakhand government",
    tags: ["vishnu", "char-dham", "himalayas", "badrinath", "vaishnavism"],
  },
  {
    slug: "dwarka",
    id: "H009",
    name: "Dwarkadhish Temple",
    type: "temple",
    location: { city: "Dwarka", state: "Gujarat", country: "India" },
    primaryFigure: "Lord Krishna (Dwarkadhish)",
    faith: "Hindu — Vaishnavism (Pushtimarg)",
    icon: "🦚",
    theme: { bg: "bg-indigo-50", nav: "bg-indigo-800", navText: "text-white", accent: "bg-indigo-700", accentText: "text-white", badge: "bg-indigo-100", badgeText: "text-indigo-800" },
    description: "One of the four sacred Char Dhams, Dwarka is the legendary kingdom of Lord Krishna. The temple follows the Pushtimarg tradition — seva here is an act of serving the Lord as a personal, beloved deity.",
    significance: "Dwarka is the westernmost Char Dham and represents Krishna's earthly twilight — a bittersweet, deeply devotional stop.",
    auspiciousDays: ["Janmashtami", "Ekadashi", "Purnima", "Fridays"],
    rituals: [
      {
        id: "individual-bhog",
        name: "Individual Bhog Offering",
        description: "Single food offering (bhog) to Lord Dwarkadhish through the temple's Pushtimarg seva system",
        offerings: "Sweets, fruits, Tulsi, Panchamrit",
        duration: "1 bhog slot",
        price: 12,
        fees: [
          { name: "Pushtimarg Seva Coordination", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & International Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 4 },
        ],
        includes: ["Individual bhog in your name", "Photo from temple seva book", "Prasad shipped"],
        livestream: false,
        source: "Dwarkadhish Temple Individual Bhog: ₹701 minimum. dwarkadhish.org seva section."
      },
      {
        id: "evening-combo-bhog",
        name: "Evening 4-Bhog Combo (Full Evening Worship)",
        description: "Four consecutive evening bhog offerings — the standard full-evening worship package at Dwarkadhish",
        offerings: "Four rounds: sweets, rice, fruits, incense + lamps",
        duration: "Evening aarti block (~2 hours)",
        price: 89,
        fees: [
          { name: "Pushtimarg Seva Coordination", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Blessed Items Packaging & Dispatch", amount: 3 },
        ],
        includes: ["All 4 evening bhogs in your name", "Video of the seva", "Peacock feather + blessed items shipped"],
        livestream: false,
        source: "Dwarkadhish Evening 4-Bhog Combo: ₹7,001. dwarkadhish.org — temple Pushtimarg seva system."
      },
    ],
    festivals: ["Janmashtami", "Holi", "Annakut"],
    diaspora: ["USA", "UK", "Canada", "Kenya", "Fiji"],
    lifeProblems: ["Devotion", "Family welfare", "Courage", "Love"],
    trustNotes: null,
    tags: ["krishna", "char-dham", "gujarat", "dwarka", "vaishnavism"],
  },

  // ── SIKH GURDWARAS ─────────────────────────────────────────────────────────
  {
    slug: "golden-temple",
    id: "S001",
    name: "Harmandir Sahib (Sri Darbar Sahib)",
    type: "gurdwara",
    location: { city: "Amritsar", state: "Punjab", country: "India" },
    primaryFigure: "Guru Arjan Dev Ji (compiled Adi Granth here)",
    faith: "Sikh",
    icon: "🌟",
    theme: { bg: "bg-amber-50", nav: "bg-blue-900", navText: "text-white", accent: "bg-blue-800", accentText: "text-white", badge: "bg-blue-100", badgeText: "text-blue-900" },
    description: "The holiest shrine in Sikhism, Sri Harmandir Sahib shines in gold at the center of Amrit Sarovar in Amritsar. The Akhand Path and free langar run 24 hours a day, every day.",
    significance: "Built to be open on all four sides, welcoming people of every faith. The Guru Granth Sahib here is the living Guru.",
    auspiciousDays: ["Gurpurab (Guru Nanak, Guru Gobind Singh)", "Vaisakhi", "Every day"],
    rituals: [
      {
        id: "ardas",
        name: "Ardas at Sri Akal Takht (Personal Prayer)",
        description: "Personal prayer offered at Sri Akal Takht Sahib in your name — arranged through an SGPC Granthi with full family names",
        offerings: "Karah Prasad (sacred halwa)",
        duration: "1 day",
        price: 14,
        fees: [
          { name: "SGPC Granthi Coordination", amount: 5 },
          { name: "Karah Prasad Offering Fee", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & International Dispatch", amount: 4 },
        ],
        includes: ["Personal Ardas at Akal Takht with full family names", "Video of Ardas", "Hukamnama (divine message) photographed and sent", "Karah Prasad seva receipt"],
        livestream: true,
        source: "SGPC Ardas is donation-based; no fixed rate. Standard Karah Prasad offering: ₹101–₹501. Arranged via SGPC Granthi at Harmandir Sahib. sgpc.net"
      },
      {
        id: "langar-seva",
        name: "Langar Seva (Sponsor 50 Meals)",
        description: "Sponsor the free community meal in your family's name — the Golden Temple feeds 50,000–100,000 people daily",
        offerings: "Langar ingredients: dal, roti, vegetables",
        duration: "1 day",
        price: 35,
        fees: [
          { name: "Langar Coordination & Admin Fee", amount: 4 },
          { name: "Seva Certificate Processing", amount: 3 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Langar served in your family's name", "Photo + video of the langar hall", "Certificate of Seva"],
        livestream: false,
        source: "SGPC langar sponsorship: ₹1,000–₹5,000 sponsors approximately 50 meals (₹20–₹30/meal). Confirmed via SGPC UK donation portal. sgpcuk.com/booking"
      },
      {
        id: "hukamnama",
        name: "Daily Hukamnama + Ardas",
        description: "Morning divine message from Sri Guru Granth Sahib, dedicated for your intention",
        offerings: "",
        duration: "1 morning",
        price: 9,
        fees: [
          { name: "SGPC Granthi Coordination", amount: 5 },
          { name: "Karah Prasad Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "International WhatsApp Delivery", amount: 4 },
          { name: "Platform Service Fee", amount: 4 },
        ],
        includes: ["Morning Hukamnama photo sent to WhatsApp", "Granthi's Ardas for your intention", "Your name in daily prayer"],
        livestream: false,
        source: "SGPC Hukamnama is free and publicly broadcast. Small seva for personal Ardas: ₹101 Karah Prasad. sgpc.net"
      },
      {
        id: "akhand-path",
        name: "Akhand Path (48-Hour Gurbani Recitation)",
        description: "48-hour non-stop reading of the complete Sri Guru Granth Sahib — registered via SGPC system; your family names read throughout",
        offerings: "Karah Prasad, rumalas (coverings)",
        duration: "48 hours",
        price: 52,
        fees: [
          { name: "SGPC Registration Facilitation", amount: 4 },
          { name: "Certificate Processing Fee", amount: 3 },
          { name: "Video Highlights Compilation", amount: 3 },
        ],
        includes: ["48-hour scripture reading — SGPC registration ₹4,100", "Family names read throughout", "Certificate + video highlights", "WhatsApp livestream link"],
        livestream: true,
        source: "SGPC official Akhand Path sewa: ₹4,100. Wait list at SGPC Amritsar exceeds 1.3 lakh bookings (~10+ year wait). Available at affiliated gurdwaras via SGPC UK (shorter wait). sgpcuk.com/booking"
      },
    ],
    festivals: ["Vaisakhi", "Guru Nanak Jayanti", "Bandi Chhor Divas (Diwali)", "Hola Mohalla"],
    diaspora: ["Canada (~500k)", "UK (~450k)", "USA (~300k)", "Australia", "Malaysia"],
    lifeProblems: ["Spiritual guidance", "Courage", "Seva (service)", "Gratitude", "Family blessings"],
    trustNotes: "Managed by Shiromani Gurdwara Parbandhak Committee (SGPC)",
    tags: ["sikh", "gurdwara", "amritsar", "golden-temple", "ardas", "langar"],
  },
  {
    slug: "hemkund-sahib",
    id: "S002",
    name: "Hemkund Sahib",
    type: "gurdwara",
    location: { city: "Chamoli District", state: "Uttarakhand", country: "India" },
    primaryFigure: "Guru Gobind Singh Ji",
    faith: "Sikh",
    icon: "🏔️",
    theme: { bg: "bg-sky-50", nav: "bg-blue-900", navText: "text-white", accent: "bg-blue-800", accentText: "text-white", badge: "bg-sky-100", badgeText: "text-sky-900" },
    description: "Perched at 4,329 metres beside a glacial lake in the Himalayas, Hemkund Sahib is where Guru Gobind Singh Ji meditated in a previous life. Open June–October only.",
    significance: "Guru Gobind Singh wrote in the Dasam Granth that he meditated at 'Hem Kunt Parwat'. The glacial lake is considered sacred beyond measure.",
    auspiciousDays: ["Open June–October", "Gurpurab of Guru Gobind Singh"],
    rituals: [
      {
        id: "ardas-sarovar",
        name: "Ardas at the Glacial Sarovar",
        description: "Prayer at the glacial lake shrine — our trekker carries your Ardas to 4,329 metres",
        offerings: "Karah Prasad",
        duration: "1 full trek day",
        price: 28,
        fees: [
          { name: "High-Altitude Trek Coordination", amount: 5 },
          { name: "Guide Hire Facilitation", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Ardas at the lake shrine in your name", "Trek video from the high-altitude gurdwara", "Sacred glacial jal (water) shipped"],
        livestream: false,
        source: "Hemkund Sahib SGPC gurdwara is free to visit. Trek guide hire for high-altitude route: ₹1,500–₹2,500/day. Our representative treks and documents. SGPC-managed site."
      },
      {
        id: "ishnaan",
        name: "Glacial Ishnaan (Sarovar Bath) Proxy",
        description: "Ritual bath in the freezing glacial lake performed in your intention by our trekker — one of the most extreme acts of devotion in Sikhism",
        offerings: "",
        duration: "1 trek day",
        price: 35,
        fees: [
          { name: "High-Altitude Trek Coordination", amount: 5 },
          { name: "Guide Hire Facilitation", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Ishnaan performed in your name at the glacial lake", "Video of the lake and the ishnaan", "Blessed water + prasad shipped"],
        livestream: false,
        source: "SGPC manages Hemkund Sahib. Ishnaan (bath) at the glacial sarovar is free. Trek + guide hire: ₹1,500–₹3,000. Ishnaan video documentation by our guide."
      },
    ],
    festivals: ["Seasonal opening ceremony (June)"],
    diaspora: ["Canada", "UK", "USA", "Australia"],
    lifeProblems: ["Deep spiritual merit", "Guru's blessings", "Health", "Surrender"],
    trustNotes: "Managed by SGPC",
    tags: ["sikh", "gurdwara", "himalayas", "guru-gobind-singh", "glacial-lake"],
  },

  // ── DARGAHS & SUFI SHRINES ─────────────────────────────────────────────────
  {
    slug: "ajmer-sharif",
    id: "M001",
    name: "Dargah Khwaja Moinuddin Chishti",
    type: "dargah",
    location: { city: "Ajmer", state: "Rajasthan", country: "India" },
    primaryFigure: "Khwaja Moinuddin Chishti (Gharib Nawaz)",
    faith: "Islam (Chishti Sufi) — open to all",
    icon: "🌙",
    theme: { bg: "bg-green-50", nav: "bg-green-800", navText: "text-white", accent: "bg-green-700", accentText: "text-white", badge: "bg-green-100", badgeText: "text-green-800" },
    description: "The most visited dargah in the world — sacred resting place of Gharib Nawaz, 'Helper of the Poor'. Emperors and beggars alike have knelt here. The Urs draws 3 million in 6 days.",
    significance: "Akbar himself walked barefoot from Agra to Ajmer in gratitude after praying here. The Urs of Gharib Nawaz is the largest Islamic gathering in South Asia outside Hajj.",
    auspiciousDays: ["Thursdays", "Urs festival (6th Rajab)", "Shab-e-Barat", "Friday Jumma"],
    rituals: [
      {
        id: "cotton-chaddar",
        name: "Cotton Chaddar Offering",
        description: "Embroidered cotton cloth offered at the mazaar of Gharib Nawaz by an authorized Khadim — basic but complete devotional act",
        offerings: "Cotton chaddar, rose petals, attar",
        duration: "1 day",
        price: 18,
        fees: [
          { name: "Khadim Family Coordination", amount: 5 },
          { name: "Sacred Offerings Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Tabaruk Packaging & International Dispatch", amount: 3 },
        ],
        includes: ["Cotton chaddar placed at mazaar (₹1,100–₹2,500 range)", "Fatiha recited by Khadim in your name", "Video + photos from the dargah", "Tabaruk (blessed sweets) shipped"],
        livestream: false,
        source: "Ajmer Sharif cotton chaddar: ₹1,100–₹2,500 depending on quality. Online via syedajmersharif.com and ajmerdargah.in — both accept PayPal/Stripe. Gaddi Nasheen representative places it."
      },
      {
        id: "silk-chaddar",
        name: "Silk Chaddar (Premium Offering)",
        description: "Velvet or silk embroidered chaddar placed on the main mazaar — a significant act of devotion",
        offerings: "Silk/velvet embroidered chaddar, rose petals, itar",
        duration: "1 day",
        price: 75,
        fees: [
          { name: "Khadim Family Coordination", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Tabaruk Packaging & Dispatch", amount: 3 },
        ],
        includes: ["Premium silk chaddar (₹5,000–₹6,000)", "Placed at main mazaar by Khadim", "Video + photo confirmation", "Tabaruk shipped"],
        livestream: false,
        source: "Ajmer Sharif embroidered silk chaddar: ₹5,000–₹11,000. syedajmersharif.com chadar complete price guide."
      },
      {
        id: "fatiha-dua",
        name: "Fatiha & Personal Mannat (Dua)",
        description: "Fatiha recited and a personal dua made for your specific mannat (wish) at the mazaar by an authorized Khadim",
        offerings: "Rose petals, attar",
        duration: "1 day",
        price: 13,
        fees: [
          { name: "Khadim Coordination Fee", amount: 5 },
          { name: "Sacred Offerings Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Platform Service Fee", amount: 4 },
        ],
        includes: ["Fatiha at the mazaar with your name and mannat", "Personal dua with your specific wish", "Video proof from inside the dargah"],
        livestream: false,
        source: "Khadim Fatiha + personal mannat dua: ₹500–₹1,000. Authorized Khadim families at Ajmer Sharif. ajmerdargah.in"
      },
      {
        id: "urs-chaddar",
        name: "Urs Festival Chaddar",
        description: "Chaddar placed during the 6-day Urs of Gharib Nawaz — the peak devotional event, drawing 3 million pilgrims",
        offerings: "Chaddar, rose petals, dates, itar",
        duration: "Urs week (6 days, month of Rajab)",
        price: 90,
        fees: [
          { name: "Peak-Season Facilitation Surcharge", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Tabaruk Packaging & Dispatch", amount: 3 },
        ],
        includes: ["Urs-week chaddar at the mazaar", "Participation video during Urs", "Dates + tabaruk shipped"],
        livestream: false,
        source: "Urs-period chaddar premium: ₹5,000–₹8,000 (surcharge over regular rates during Urs week). syedajmersharif.com"
      },
    ],
    festivals: ["Urs of Gharib Nawaz (6 days in Rajab)", "Shab-e-Barat", "Eid"],
    diaspora: ["Pakistan", "Bangladesh", "India (Rajasthani diaspora)", "UK", "UAE"],
    lifeProblems: ["Mannat fulfillment", "Healing", "Spiritual solace", "Marriage", "Poverty relief"],
    trustNotes: "Managed by Dargah Khwaja Saheb Trust (Ministry of Minority Affairs, India)",
    tags: ["sufi", "chishti", "dargah", "ajmer", "mannat", "qalandari"],
  },
  {
    slug: "data-darbar",
    id: "M002",
    name: "Data Darbar Shrine",
    type: "dargah",
    location: { city: "Lahore", state: "Punjab", country: "Pakistan" },
    primaryFigure: "Hazrat Ali Hujwiri (Data Ganj Bakhsh)",
    faith: "Islam (Chishti Sufi) — open to all",
    icon: "⭐",
    theme: { bg: "bg-emerald-50", nav: "bg-emerald-800", navText: "text-white", accent: "bg-emerald-700", accentText: "text-white", badge: "bg-emerald-100", badgeText: "text-emerald-800" },
    description: "Data Ganj Bakhsh — the oldest and most revered Sufi shrine in Pakistan. His 11th-century text Kashf al-Mahjub is the first Sufi book in Persian. Thursday nights here are legendary.",
    significance: "Khwaja Moinuddin Chishti himself visited this shrine and said: 'Ganj Bakhsh is the light of both worlds, the perfect murshid for the imperfect.'",
    auspiciousDays: ["Thursdays", "Urs festival", "Shab-e-Qadr"],
    rituals: [
      {
        id: "chadar",
        name: "Chadar at Data Sahib's Mazaar",
        description: "Cloth offered at the mazaar of Data Ganj Bakhsh by our Lahore representative — no official online booking exists; our vetted local partner provides documentation",
        offerings: "Chadar, rose petals, attar",
        duration: "1 day",
        price: 22,
        fees: [
          { name: "Local Partner Facilitation Fee", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Tabaruk Packaging & Dispatch", amount: 3 },
        ],
        includes: ["Chadar placed at Data Sahib's mazaar", "Fatiha recited in your name", "Video proof from the dargah", "Tabaruk shipped"],
        livestream: false,
        source: "Data Darbar managed by Punjab Auqaf Dept (auqaf.punjab.gov.pk) — no commercial online chadar booking via government. Our Lahore partner facilitates. Chadar cost: PKR 1,500–3,000 (~$5–10) + service fee."
      },
      {
        id: "mannat",
        name: "Mannat Dedication at the Mazaar",
        description: "Your specific wish (mannat) presented at the mazaar with dua and Fatiha by our local representative",
        offerings: "Flowers, rose water, incense",
        duration: "1 day",
        price: 18,
        fees: [
          { name: "Local Partner Coordination", amount: 5 },
          { name: "Sacred Offerings Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
        ],
        includes: ["Mannat presented at Data Sahib's mazaar", "Fatiha + dua on your behalf", "Photo proof from inside the dargah"],
        livestream: false,
        source: "No official booking system for Data Darbar. Khadim dua arrangement: PKR 1,000–2,000 (~$4–7). Auqaf-supervised site. auqaf.punjab.gov.pk"
      },
      {
        id: "thursday-mehfil",
        name: "Thursday Night Mehfil Dedication",
        description: "Your name offered during the Thursday night devotional gathering — one of South Asia's most famous weekly spiritual events",
        offerings: "Rose petals",
        duration: "1 night",
        price: 14,
        fees: [
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 5 },
          { name: "Rose Water Packaging & Dispatch", amount: 4 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Name in Thursday mehfil at Data Darbar", "Audio/video clip from the gathering", "Blessed rose water shipped"],
        livestream: false,
        source: "Thursday mehfil at Data Darbar is free to all. Our representative attends and makes dedication. Arrangement fee: PKR 500–1,000 (~$2–4)."
      },
    ],
    festivals: ["Annual Urs", "Shab-e-Barat", "Eid ul-Fitr"],
    diaspora: ["Pakistani diaspora UK", "Canada", "UAE", "USA"],
    lifeProblems: ["Wish fulfillment", "Spiritual knowledge", "Blessings", "Marriage", "Career"],
    trustNotes: "Managed by Auqaf Department, Punjab, Pakistan",
    tags: ["sufi", "pakistan", "lahore", "data-sahib", "mannat"],
  },
  {
    slug: "nizamuddin-dargah",
    id: "M003",
    name: "Hazrat Nizamuddin Dargah",
    type: "dargah",
    location: { city: "New Delhi", state: "Delhi", country: "India" },
    primaryFigure: "Hazrat Nizamuddin Auliya",
    faith: "Islam (Chishti Sufi) — open to all",
    icon: "🕌",
    theme: { bg: "bg-teal-50", nav: "bg-teal-800", navText: "text-white", accent: "bg-teal-700", accentText: "text-white", badge: "bg-teal-100", badgeText: "text-teal-800" },
    description: "The dargah of Hazrat Nizamuddin Auliya has been a center of spiritual life for 700 years. The Thursday evening qawwali has run unbroken since the 14th century. Amir Khusrow's tomb is here too.",
    significance: "Nizamuddin's teaching was love — 'Love is God and God is Love.' His disciple Amir Khusrow gave India the sitar and qawwali.",
    auspiciousDays: ["Thursdays", "Urs", "Basant Panchami"],
    rituals: [
      {
        id: "qawwali-dedication",
        name: "Thursday Qawwali Dedication (700-Year Tradition)",
        description: "The unbroken Thursday qawwali since the 14th century — your name entered by our representative who attends the 6–9 PM session",
        offerings: "Rose petals, incense",
        duration: "1 night (~6–9 PM)",
        price: 16,
        fees: [
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Blessed Items Packaging & Dispatch", amount: 4 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Name in Thursday qawwali at Hazrat Nizamuddin", "Video recording of the session", "Blessed rose petals + tabaruk shipped"],
        livestream: false,
        source: "Thursday qawwali at Nizamuddin is free to all. nizamuddinaulia.org accepts flexible online donations for chadar, flowers, langar. Our arrangement includes representative + documentation."
      },
      {
        id: "chadar-flowers",
        name: "Chadar & Rose Offering",
        description: "Chadar and fresh roses offered at the mazaar of Hazrat Nizamuddin Auliya by a Khadim",
        offerings: "Chadar (₹1,500 range), fresh roses",
        duration: "1 day",
        price: 22,
        fees: [
          { name: "Khadim Coordination Fee", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Chadar + rose offering at the mazaar", "Fatiha recited by Khadim", "Photo with your dedication"],
        livestream: false,
        source: "Nizamuddin chadar from lane vendors: ₹500–₹5,000. Our representative arranges ₹1,500 chadar + Khadim Fatiha. nizamuddinaulia.org donation portal (flexible amount)."
      },
      {
        id: "fatiha",
        name: "Fatiha Khwani at the Mazaar",
        description: "Fatiha recited and personal dua offered at the mazaar by an authorized Khadim for your intention",
        offerings: "Fresh flowers, incense",
        duration: "1 day",
        price: 13,
        fees: [
          { name: "Khadim Coordination Fee", amount: 5 },
          { name: "Sacred Offerings Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Tabaruk Packaging & Dispatch", amount: 5 },
        ],
        includes: ["Fatiha at Hazrat Nizamuddin's mazaar", "Personal dua for your intention", "Video proof", "Blessed tabaruk shipped"],
        livestream: false,
        source: "Nizamuddin Khadim Fatiha: ₹300–₹700 typical. nizamuddinaulia.org accepts online donations. Nizami family (hereditary managers) do not have a fixed price list."
      },
    ],
    festivals: ["Urs of Nizamuddin Auliya", "Urs of Amir Khusrow", "Basant (yellow flower festival)"],
    diaspora: ["India (Delhi/UP diaspora)", "Pakistan", "Bangladesh", "UK"],
    lifeProblems: ["Spiritual love", "Healing", "Wish fulfillment", "Artistic blessings"],
    trustNotes: null,
    tags: ["sufi", "chishti", "delhi", "qawwali", "amir-khusrow"],
  },

  // ── CHURCHES & CHRISTIAN SHRINES ───────────────────────────────────────────
  {
    slug: "velankanni",
    id: "C001",
    name: "Basilica of Our Lady of Good Health",
    type: "church",
    location: { city: "Velankanni", state: "Tamil Nadu", country: "India" },
    primaryFigure: "Virgin Mary (Our Lady of Good Health / Arokia Matha)",
    faith: "Christian — Roman Catholic",
    icon: "⛪",
    theme: { bg: "bg-sky-50", nav: "bg-sky-800", navText: "text-white", accent: "bg-sky-700", accentText: "text-white", badge: "bg-sky-100", badgeText: "text-sky-900" },
    description: "Called the 'Lourdes of the East', Our Lady of Velankanni has healed the sick since the 16th century. The September feast draws over a million pilgrims of all faiths.",
    significance: "Three miraculous apparitions of Mary are recorded here. The fishermen who built the first chapel survived a storm after praying to her.",
    auspiciousDays: ["Fridays", "September feast (Aug 29–Sep 8)", "Christmas", "Good Friday"],
    rituals: [
      {
        id: "candle",
        name: "Candle Lighting & Prayer",
        description: "Candle lit before Our Lady with your intention by our local representative at the Offering Centre",
        offerings: "Candle, flowers",
        duration: "1 day",
        price: 9,
        fees: [
          { name: "Local Representative Fee", amount: 5 },
          { name: "Sacred Items Procurement", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Blessed Medal Packaging & International Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Candle lit at Our Lady's feet", "Your intention prayed aloud", "Photo of lit candle", "Blessed miraculous medal shipped"],
        livestream: false,
        source: "Velankanni candle offering: ₹20–₹500 at the Offering Centre. Contact: info@vailankannishrine.net / +91-4365-263540. vailankannishrine.net"
      },
      {
        id: "novena",
        name: "9-Day Novena Dedication",
        description: "Your name and intention entered for the 9-day Novena prayers at the Basilica",
        offerings: "Candles, flowers",
        duration: "9 days",
        price: 18,
        fees: [
          { name: "Parish Coordination Fee", amount: 5 },
          { name: "9-Day Daily Update Service", amount: 3 },
          { name: "Novena Booklet & Medal Dispatch", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Name in 9-day novena at the Basilica", "Daily WhatsApp updates", "Novena booklet + blessed miraculous medal shipped"],
        livestream: false,
        source: "Velankanni novena: contact shrine directly. Mass intention per day: ₹50 (weekday) – ₹100 (Sunday/feast day) at affiliated Velankanni shrines. 9-day = ₹450–₹900 total. vailankannishrine.net"
      },
      {
        id: "mass-offering",
        name: "Holy Mass Intention",
        description: "Mass offered for your specific intention by a resident priest at the Basilica",
        offerings: "Candles",
        duration: "1 hour",
        price: 13,
        fees: [
          { name: "Parish Coordination Fee", amount: 5 },
          { name: "Mass Card Processing", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Blessed Medal Packaging & Dispatch", amount: 5 },
        ],
        includes: ["Mass offered for your intention", "Mass card (photo sent)", "Video of Mass from our representative", "Blessed miraculous medal shipped"],
        livestream: false,
        source: "Velankanni mass intention: ₹50–₹150. Regional Catholic shrine standard rate. Arrange via info@vailankannishrine.net or +91-4365-263540. vailankannishrine.net"
      },
      {
        id: "votive",
        name: "Votive Thanksgiving Offering",
        description: "Thanksgiving offering placed at the shrine for a grace already received",
        offerings: "Votive lamp, flowers",
        duration: "1 day",
        price: 12,
        fees: [
          { name: "Local Representative Fee", amount: 5 },
          { name: "Sacred Items Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Blessed Rosary Packaging & Dispatch", amount: 5 },
        ],
        includes: ["Thanksgiving votive placed in your name at Offering Centre", "Photo from the shrine", "Blessed rosary shipped"],
        livestream: false,
        source: "Votive offerings at Velankanni Offering Centre: ₹100–₹500. vailankannishrine.net"
      },
    ],
    festivals: ["Annual Feast (Aug 29–Sep 8)", "Christmas", "Good Friday", "Assumption (Aug 15)"],
    diaspora: ["Tamil diaspora Malaysia, Singapore, UK, UAE", "Goan diaspora"],
    lifeProblems: ["Healing", "Miracles", "Safety at sea", "Gratitude", "Children"],
    trustNotes: "Managed by the Diocese of Tanjore",
    tags: ["mary", "catholic", "velankanni", "miracle", "healing"],
  },
  {
    slug: "bom-jesus-goa",
    id: "C002",
    name: "Basilica of Bom Jesus, Goa",
    type: "church",
    location: { city: "Old Goa", state: "Goa", country: "India" },
    primaryFigure: "St. Francis Xavier",
    faith: "Christian — Roman Catholic",
    icon: "✝️",
    theme: { bg: "bg-blue-50", nav: "bg-blue-900", navText: "text-white", accent: "bg-blue-800", accentText: "text-white", badge: "bg-blue-100", badgeText: "text-blue-900" },
    description: "A UNESCO World Heritage Site (1605), this baroque basilica houses the incorrupt body of St. Francis Xavier — the 'Apostle of the East' who evangelized across India, Southeast Asia and Japan. His body has not decayed in 450+ years.",
    significance: "The Exposition of St. Francis Xavier's relics (every 10 years) is one of the world's largest Catholic gatherings. His intercession is sought for healing and mission.",
    auspiciousDays: ["Feast of St. Francis Xavier (Dec 3)", "6th of each month (special chapel Mass)", "Christmas"],
    rituals: [
      {
        id: "mass",
        name: "Holy Mass Intention at St. Francis Xavier's Basilica",
        description: "Mass offered at the feet of St. Francis Xavier's incorrupt body for your specific intention by a Jesuit priest",
        offerings: "Candles, flowers",
        duration: "1 hour",
        price: 11,
        fees: [
          { name: "Parish Coordination Fee", amount: 5 },
          { name: "Mass Card Processing", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Blessed Medal Packaging & Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Mass for your intention at this UNESCO site", "Mass card (photo)", "Video from our Goa representative", "Blessed St. Francis Xavier medal shipped"],
        livestream: false,
        source: "Bom Jesus mass intention: ₹50–₹150. Confirmed by visitor accounts; sacristy registration in person or by phone. No official online booking system."
      },
      {
        id: "candle-relic",
        name: "Candle at the Relic Chapel",
        description: "Candle lit before the incorrupt, undecayed relics of St. Francis Xavier — the only place in the world this is possible",
        offerings: "Candle",
        duration: "1 day",
        price: 9,
        fees: [
          { name: "UNESCO Heritage Site Access Fee", amount: 5 },
          { name: "Local Representative Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 5 },
          { name: "Blessed Medal Packaging & Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Candle lit before the incorrupt relics", "Photo with relic chapel visible", "Blessed St. Francis Xavier medal shipped"],
        livestream: false,
        source: "Candle at Bom Jesus Relic Chapel: ₹50–₹150 depending on candle size. Arranged by our Goa representative. No official booking system exists."
      },
    ],
    festivals: ["Feast of St. Francis Xavier (Dec 3)", "Christmas", "Easter"],
    diaspora: ["Goan diaspora in UK, Portugal, UAE, Australia"],
    lifeProblems: ["Healing", "Mission", "Faith", "Forgiveness"],
    trustNotes: "Managed by the Archdiocese of Goa and Daman",
    tags: ["catholic", "goa", "st-francis-xavier", "relic", "heritage"],
  },

  // ── BUDDHIST ───────────────────────────────────────────────────────────────
  {
    slug: "mahabodhi-bodhgaya",
    id: "B001",
    name: "Mahabodhi Temple",
    type: "monastery",
    location: { city: "Bodh Gaya", state: "Bihar", country: "India" },
    primaryFigure: "Siddhartha Gautama (the Buddha)",
    faith: "Buddhist",
    icon: "☸️",
    theme: { bg: "bg-yellow-50", nav: "bg-yellow-800", navText: "text-white", accent: "bg-yellow-700", accentText: "text-white", badge: "bg-yellow-100", badgeText: "text-yellow-900" },
    description: "The most sacred site in Buddhism — where Siddhartha Gautama attained enlightenment under the Bodhi tree. The current Bodhi tree is a direct descendant of the original. UNESCO World Heritage Site.",
    significance: "The Diamond Throne (Vajrasana) on which Buddha sat is believed to be the navel of the universe. Meditation here carries extraordinary power.",
    auspiciousDays: ["Buddha Purnima (May)", "Vassa (monsoon retreat)", "Dalai Lama teachings (January)"],
    rituals: [
      {
        id: "lamp-offering",
        name: "Oil Lamp Offering at the Bodhi Tree",
        description: "Lamp lit at the foot of the Bodhi tree — the exact spot where the Buddha attained enlightenment — arranged via a resident monk",
        offerings: "Oil lamp, marigold flowers",
        duration: "1 evening",
        price: 8,
        fees: [
          { name: "Monastery Coordination Fee", amount: 5 },
          { name: "Sacred Items Procurement", amount: 5 },
          { name: "Digital Documentation Package", amount: 5 },
          { name: "Blessed Bodhi Leaf & Incense Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Lamp lit at the Bodhi tree", "Photo proof with tree visible", "Blessed Bodhi leaf + incense shipped"],
        livestream: false,
        source: "Mahabodhi Temple entry: free. Oil lamp from market stalls: ₹20–₹200. Monk arranges and photographs for ₹200–₹500 dana. bodhgayatemple.com — no official puja booking system."
      },
      {
        id: "pradakshina",
        name: "Pradakshina (Circumambulation of Bodhi Tree)",
        description: "Ritual walk around the sacred Bodhi tree and Vajrasana with prayers and flowers — performed by a Buddhist monk in your name",
        offerings: "Flowers, candles, incense",
        duration: "30 minutes",
        price: 12,
        fees: [
          { name: "Monastery Coordination Fee", amount: 5 },
          { name: "Sacred Items Procurement", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Blessed Bodhi Leaf Packaging & Dispatch", amount: 5 },
        ],
        includes: ["Pradakshina by resident monk in your name", "Video at the Bodhi tree", "Blessed Bodhi leaf shipped"],
        livestream: false,
        source: "Mahabodhi Temple entry free. Monk-arranged puja/pradakshina: ₹500–₹1,000 dana. bodhgayatemple.com — the BTMC has no individual puja booking; arranged via resident monasteries."
      },
      {
        id: "meditation-dedication",
        name: "1-Hour Monk Meditation at Vajrasana",
        description: "A resident monk meditates for one hour at the Diamond Throne (the exact spot of enlightenment) and dedicates the merit to you",
        offerings: "",
        duration: "1 hour",
        price: 28,
        fees: [
          { name: "Monastery Coordination Fee", amount: 4 },
          { name: "Merit Dedication Certificate", amount: 3 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["1-hour seated meditation at Vajrasana in your name", "Video of the session at Diamond Throne", "Merit dedication certificate from the monastery"],
        livestream: false,
        source: "Resident monasteries (Tibetan, Thai, Burmese) arrange dedicated meditations for donors. Typical dana: ₹1,500–₹2,500 for 1-hour dedicated meditation. FPMT and similar org rates confirmed."
      },
    ],
    festivals: ["Buddha Purnima", "Bodhi Day (Dec 8 for Zen)", "Dalai Lama teachings (January)"],
    diaspora: ["Sri Lanka", "Myanmar", "Thailand", "Japan", "Korea", "Tibet", "Western Buddhists globally"],
    lifeProblems: ["Enlightenment", "Merit accumulation", "Peace", "Ancestor merit", "Suffering relief"],
    trustNotes: "UNESCO World Heritage Site; managed by Bodh Gaya Temple Management Committee (joint Hindu-Buddhist body)",
    tags: ["buddhism", "buddha", "bodhi-tree", "enlightenment", "meditation", "heritage"],
  },

  // ── JAIN ──────────────────────────────────────────────────────────────────
  {
    slug: "palitana",
    id: "J001",
    name: "Palitana Temples (Shatrunjaya Hill)",
    type: "temple",
    location: { city: "Palitana", state: "Gujarat", country: "India" },
    primaryFigure: "Shri Adinath (Rishabhanatha) — first Jain Tirthankara",
    faith: "Jain",
    icon: "🕊️",
    theme: { bg: "bg-white", nav: "bg-stone-800", navText: "text-white", accent: "bg-stone-700", accentText: "text-white", badge: "bg-stone-100", badgeText: "text-stone-800" },
    description: "The holiest pilgrimage in Jainism — 900+ marble temples crown Shatrunjaya Hill. The 3,800-step climb is itself a form of devotion. No overnight stay allowed — it belongs to the gods alone.",
    significance: "Over 23 crore Jains are said to have attained liberation here. Every Jain aspires to visit at least once.",
    auspiciousDays: ["Paryushana", "Mahavir Jayanti", "Kartik Purnima", "Phalgun Purnima"],
    rituals: [
      {
        id: "snatra-puja",
        name: "Snatra Puja (Abhishek of Adinath)",
        description: "Bathing the principal Adinath deity with milk and saffron water — our authorized Jain pujari climbs all 3,800 steps and performs on your behalf",
        offerings: "Milk, saffron water, sandalwood paste, flowers",
        duration: "30–45 minutes",
        price: 32,
        fees: [
          { name: "Pujari Climb Coordination", amount: 4 },
          { name: "Sacred Offerings Procurement", amount: 3 },
          { name: "Digital Documentation Package", amount: 3 },
        ],
        includes: ["Snatra Puja at main Adinath temple by authorized pujari", "Full video including the climb", "Blessed saffron + sandalwood shipped"],
        livestream: false,
        source: "Jain pujari arrangement at Palitana: ₹1,500–₹3,000 for full Snatra Puja including climb. No government booking system — organized via Shatrunjaya temple pujari association."
      },
      {
        id: "navkar-mantra",
        name: "Navkar Mantra (108 Recitations)",
        description: "108 recitations of the universal Jain prayer at the hilltop main temple in your name",
        offerings: "",
        duration: "45 minutes",
        price: 18,
        fees: [
          { name: "Pujari Coordination & Booking", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Navkar Mala Packaging & Dispatch", amount: 5 },
        ],
        includes: ["108 Navkar Mantra in your name at the temple", "Video", "Jain prayer mala (navkar mala) shipped"],
        livestream: false,
        source: "Jain pujari arrangement at Palitana for 108 Navkar Mantra recitation: ₹500–₹1,500 depending on priest and count."
      },
    ],
    festivals: ["Paryushana (Aug/Sep)", "Mahavir Jayanti (Mar/Apr)", "Diwali (Jain New Year)"],
    diaspora: ["USA (Jain community)", "UK", "East Africa (Kenyan Jains)", "Canada"],
    lifeProblems: ["Purity", "Salvation (moksha)", "Non-violence", "Karmic cleansing"],
    trustNotes: null,
    tags: ["jain", "tirthankara", "gujarat", "shatrunjaya", "liberation"],
  },

  // ── GURU / ASHRAM PAGES ───────────────────────────────────────────────────
  {
    slug: "osho-ashram",
    id: "G001",
    name: "Osho International Meditation Resort",
    type: "ashram",
    location: { city: "Pune", state: "Maharashtra", country: "India" },
    primaryFigure: "Osho (Bhagwan Shree Rajneesh)",
    faith: "Universal — no religion required",
    icon: "🌸",
    theme: { bg: "bg-purple-50", nav: "bg-purple-900", navText: "text-white", accent: "bg-purple-700", accentText: "text-white", badge: "bg-purple-100", badgeText: "text-purple-900" },
    description: "The meditation resort where Osho lived and taught — one of the world's largest meditation centers. His 3,000+ talks translated into 60+ languages. 100+ meditation methods run daily.",
    significance: "Osho said: 'The moment you accept yourself, you become beautiful.' His samadhi is at the center of the campus. Entry requires a pass; prices are publicly listed by the resort.",
    auspiciousDays: ["Osho Enlightenment Day (March 21)", "Osho Mahaparinirvana Day (January 19)", "Daily"],
    rituals: [
      {
        id: "samadhi-meditation",
        name: "Meditation at Osho's Samadhi (1-Day Pass)",
        description: "Our officiant purchases the official 1-day entry pass and meditates at Osho's samadhi for 1 hour with your name and intention — video sent same day",
        offerings: "",
        duration: "1 hour at samadhi",
        price: 29,
        fees: [
          { name: "Resort Pass Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Signed Photo Card Processing", amount: 3 },
        ],
        includes: ["1-day resort entry pass at official international rate (₹2,050)", "1-hour silent meditation at Osho's samadhi", "Video of the Samadhi Hall", "Signed photo card of the session"],
        livestream: false,
        source: "Osho Resort 1-Day Entry Pass: ₹2,050 (international visitors) / ₹1,050 (Indian nationals). osho.com/osho-meditation-resort/rates-offers/seasonal-rates"
      },
      {
        id: "dynamic-meditation-3day",
        name: "Dynamic Meditation — 3-Day Dedication",
        description: "Our officiant attends the 6 AM Dynamic Meditation for 3 consecutive days, dedicating merit to you — video update sent each morning",
        offerings: "",
        duration: "1 hour x 3 days",
        price: 68,
        fees: [
          { name: "Resort Pass Procurement", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Digital Music Album Delivery", amount: 2 },
        ],
        includes: ["3-day resort pass at official international rate (₹5,200)", "Dynamic Meditation in your name for 3 mornings", "Daily video updates via WhatsApp", "Osho meditation music album (digital link)"],
        livestream: false,
        source: "Osho Resort 3-Day Entry Pass: ₹5,200 (international) / ₹2,650 (Indian). osho.com/osho-meditation-resort/rates-offers/seasonal-rates"
      },
    ],
    festivals: ["Osho Enlightenment Day (March 21)", "Osho Mahaparinirvana Day (January 19)"],
    diaspora: ["Germany", "USA", "Japan", "Israel", "Netherlands", "Worldwide"],
    lifeProblems: ["Inner freedom", "Creativity", "Love & relationships", "Existential questions", "Meditation"],
    trustNotes: "Run by Osho International Foundation (private, non-religious organization)",
    tags: ["osho", "meditation", "pune", "consciousness", "universal", "rajneesh"],
  },
  {
    slug: "amma-amritapuri",
    id: "G002",
    name: "Amritapuri Ashram (Mata Amritanandamayi)",
    type: "ashram",
    location: { city: "Kollam", state: "Kerala", country: "India" },
    primaryFigure: "Mata Amritanandamayi (Amma)",
    faith: "Hindu — Universal",
    icon: "💛",
    theme: { bg: "bg-pink-50", nav: "bg-pink-800", navText: "text-white", accent: "bg-pink-700", accentText: "text-white", badge: "bg-pink-100", badgeText: "text-pink-900" },
    description: "The home ashram of Amma — the hugging saint who has embraced over 40 million people. Her ashram on a Kerala backwater island is a center of devotion, service, and spiritual inquiry.",
    significance: "Amma says: 'My religion is love.' Her darshan (the embrace) and all ashram programs are completely free. Accommodation is available at minimal cost.",
    auspiciousDays: ["Amma's birthday (Karkidakam/September)", "Devi Bhava nights", "Shivaratri"],
    rituals: [
      {
        id: "darshan-dedication",
        name: "Darshan Dedication at Amritapuri",
        description: "Our representative attends Amma's darshan program, offers dedicated prayers in your name, and documents the visit. Darshan (Amma's hug) is completely free — our fee covers the documentation and prasad",
        offerings: "Flowers",
        duration: "1 full darshan day",
        price: 19,
        fees: [
          { name: "Representative Attendance Fee", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & International Dispatch", amount: 4 },
          { name: "Platform Service Fee", amount: 2 },
        ],
        includes: ["Dedicated prayer during Amma's darshan program", "Video of the ashram and darshan hall", "Blessed prasad from Amma's kitchen shipped"],
        livestream: true,
        source: "Amritapuri Ashram entry: free. Amma's darshan: free. Accommodation (if needed for timing): ₹600/night international. amritapuri.org/ashram/faq — our representative attends and documents."
      },
      {
        id: "devi-bhava",
        name: "Devi Bhava Night Dedication",
        description: "During Devi Bhava — when Amma embodies the Divine Mother — your name is offered and prayers dedicated. These rare events draw thousands worldwide.",
        offerings: "Flowers, coconut",
        duration: "1 full night event",
        price: 38,
        fees: [
          { name: "Special Event Coordination Fee", amount: 4 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Kumkum & Prasad Packaging & Dispatch", amount: 3 },
        ],
        includes: ["Name offered at Devi Bhava program", "Video of the event atmosphere", "Kumkum + prasad from the event shipped"],
        livestream: false,
        source: "Devi Bhava programs at Amritapuri: free entry, no ticket. Our representative attends, dedicates prayers, and documents. Accommodation if overnight: ₹600/night. amritapuri.org for schedule."
      },
    ],
    festivals: ["Amma's Birthday (September)", "Devi Bhava programs", "Onam", "Shivaratri"],
    diaspora: ["USA", "Europe", "Japan", "Australia", "Global Amma following"],
    lifeProblems: ["Love", "Compassion", "Healing", "Grief", "Surrender"],
    trustNotes: "Run by Mata Amritanandamayi Math (registered charitable trust)",
    tags: ["amma", "hugging-saint", "kerala", "devi", "universal-love"],
  },
  {
    slug: "iskcon-vrindavan",
    id: "G003",
    name: "ISKCON Vrindavan (Krishna Balaram Temple)",
    type: "temple",
    location: { city: "Vrindavan", state: "Uttar Pradesh", country: "India" },
    primaryFigure: "Lord Krishna & Balarama / A.C. Bhaktivedanta Swami Prabhupada",
    faith: "Hindu — Gaudiya Vaishnavism (Hare Krishna)",
    icon: "🦚",
    theme: { bg: "bg-orange-50", nav: "bg-orange-800", navText: "text-white", accent: "bg-orange-700", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-900" },
    description: "The main ISKCON temple in Vrindavan — the land of Krishna's childhood. Founded by Srila Prabhupada, whose samadhi is here. Seva prices are publicly listed on their official donation portal.",
    significance: "Vrindavan is said to be a spiritual realm descended to Earth. 5,000+ temples dot the town. Full seva price list available at iskconvrindavandonation.com.",
    auspiciousDays: ["Janmashtami", "Radhashtami", "Ekadashi", "Holi (Phalguna)"],
    rituals: [
      {
        id: "sandhya-aarti-seva",
        name: "Sandhya Aarti Seva (7 PM)",
        description: "Your name as the day's sponsor at the spectacular 7 PM evening aarti of Krishna and Balarama — official ISKCON seva with published price",
        offerings: "Ghee lamps, flowers, incense",
        duration: "45 minutes",
        price: 44,
        fees: [
          { name: "ISKCON Booking Coordination", amount: 3 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Tulsi & Prasad Packaging & Dispatch", amount: 3 },
        ],
        includes: ["Sandhya Aarti seva in your name (official rate: ₹3,501)", "Video of the aarti sent to WhatsApp", "Tulsi + prasad shipped"],
        livestream: false,
        source: "ISKCON Vrindavan Sandhya Aarti Seva: ₹3,501. iskconvrindavandonation.com/daily-seva"
      },
      {
        id: "vigraha-abhishek",
        name: "Vigraha Abhishek (1 Altar)",
        description: "Sacred bathing of the presiding deities (Krishna Balaram or Gaura Nitai) — official ISKCON Vigraha Seva with published price",
        offerings: "Panchamrit (5 sacred liquids), flowers, Tulsi",
        duration: "45 minutes",
        price: 62,
        fees: [
          { name: "ISKCON Booking Coordination", amount: 3 },
          { name: "Digital Documentation Package", amount: 3 },
          { name: "Tulsi Mala & Prasad Packaging & Dispatch", amount: 3 },
        ],
        includes: ["Abhishek at one of three altars in your name (official rate: ₹5,000)", "Full abhishek video", "Tulsi mala + prasad shipped"],
        livestream: false,
        source: "ISKCON Vrindavan Vigraha Abhishek (1 altar): ₹5,000. iskconvrindavandonation.com/vigraha-seva"
      },
      {
        id: "naam-japa",
        name: "10,000 Hare Krishna Naam Japa",
        description: "A devotee chants the Hare Krishna Maha-Mantra 10,000 times for you — common practice for absent devotees or those seeking healing",
        offerings: "",
        duration: "2 hours",
        price: 16,
        fees: [
          { name: "Devotee Network Coordination", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Tulsi Mala Packaging & Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["10,000 Hare Krishna Maha-Mantra in your name", "Video of chanting session", "Tulsi mala (japa beads) shipped"],
        livestream: false,
        source: "Not an official ISKCON catalog item; arranged via Vrindavan devotee network. Standard rate for 10,000 japa dedication: ₹1,000–₹1,500."
      },
    ],
    festivals: ["Janmashtami (grand celebration)", "Radhashtami", "Holi (Phalguna)", "Govardhan Puja"],
    diaspora: ["Hare Krishna devotees globally", "USA", "UK", "Russia", "Australia", "Brazil"],
    lifeProblems: ["Devotion", "Purification", "Relationship with God", "Spiritual community"],
    trustNotes: "Run by ISKCON (International Society for Krishna Consciousness)",
    tags: ["krishna", "hare-krishna", "vrindavan", "iskcon", "prabhupada", "vaishnavism"],
  },
  {
    slug: "ramakrishna-belur-math",
    id: "G004",
    name: "Belur Math (Ramakrishna Math & Mission HQ)",
    type: "samadhi",
    location: { city: "Belur", state: "West Bengal", country: "India" },
    primaryFigure: "Sri Ramakrishna Paramahamsa / Swami Vivekananda",
    faith: "Hindu — Vedanta (universal)",
    icon: "🙏",
    theme: { bg: "bg-orange-50", nav: "bg-orange-900", navText: "text-white", accent: "bg-orange-800", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-900" },
    description: "Headquarters of the Ramakrishna Math and Mission, established by Swami Vivekananda on the Ganges. The architecture integrates Hindu, Islamic, and Christian elements. Sri Ramakrishna's relics are enshrined here.",
    significance: "Vivekananda said: 'Each soul is potentially divine.' Belur Math does not operate on a commercial puja model — all donations are voluntary and open-ended.",
    auspiciousDays: ["Ramakrishna Jayanti (Feb/Mar)", "Vivekananda Jayanti (Jan 12)", "Durga Puja"],
    rituals: [
      {
        id: "puja-dedication",
        name: "Thakur Puja Dedication",
        description: "Your name entered in the daily worship (Thakur Seva) of Sri Ramakrishna at Belur Math — arranged through the official donation system with a specific dedication",
        offerings: "Flowers, incense, prasad",
        duration: "1 day",
        price: 14,
        fees: [
          { name: "Math Office Coordination", amount: 5 },
          { name: "Digital Documentation Package", amount: 4 },
          { name: "Prasad Packaging & International Dispatch", amount: 5 },
          { name: "Platform Service Fee", amount: 3 },
        ],
        includes: ["Name in Thakur Puja at Belur Math", "Video or photo of the dedication sent", "Prasad from the shrine kitchen shipped"],
        livestream: false,
        source: "Belur Math online donation minimum: ₹100 (any purpose). Permanent Fund minimum: ₹5,000. Specific puja dedication arranged via math office. donations.belurmath.org — entry to math is free."
      },
    ],
    festivals: ["Ramakrishna Jayanti", "Vivekananda Jayanti", "Durga Puja (grand)", "Kali Puja"],
    diaspora: ["USA", "UK", "Germany", "Global Vedanta followers"],
    lifeProblems: ["Universal spirituality", "Service (karma yoga)", "Philosophical inquiry", "Harmony of religions"],
    trustNotes: "Managed by Ramakrishna Math and Ramakrishna Mission (registered trust)",
    tags: ["ramakrishna", "vivekananda", "vedanta", "universal", "west-bengal"],
  },
]
