export type Ritual = {
  id: string
  name: string
  description: string
  offerings: string
  duration: string
  price: number
  includes: string[]
  livestream: boolean
}

export type Place = {
  slug: string
  id: string
  name: string
  type: "temple" | "gurdwara" | "dargah" | "church" | "monastery" | "ashram" | "samadhi" | "shrine" | "mosque"
  location: { city: string; state: string; country: string }
  primaryFigure: string
  faith: string
  icon: string
  theme: { bg: string; nav: string; navText: string; accent: string; accentText: string; badge: string; badgeText: string }
  description: string
  significance: string
  auspiciousDays: string[]
  rituals: Ritual[]
  festivals: string[]
  diaspora: string[]
  lifeProblems: string[]
  trustNotes: string | null
  tags: string[]
}

export const places: Place[] = [
  // ── HINDU TEMPLES ──────────────────────────────────────────────────────────
  {
    slug: "kashi-vishwanath",
    id: "H001",
    name: "Kashi Vishwanath Temple",
    type: "temple",
    location: { city: "Varanasi", state: "Uttar Pradesh", country: "India" },
    primaryFigure: "Lord Shiva (Vishwanath)",
    faith: "Hindu — Shaivism",
    icon: "🔱",
    theme: { bg: "bg-orange-50", nav: "bg-orange-800", navText: "text-white", accent: "bg-orange-600", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-800" },
    description: "One of the twelve Jyotirlingas and the most sacred temple of Lord Shiva, situated on the banks of the Ganges in Varanasi — the city of liberation. A darshan here is believed to grant moksha.",
    significance: "Dying in Varanasi is said to guarantee liberation, as Shiva himself whispers the Taraka mantra into the dying person's ear.",
    auspiciousDays: ["Mondays", "Mahashivratri", "Shravan month", "Pradosh"],
    rituals: [
      { id: "rudrabhishek", name: "Rudrabhishek", description: "Sacred ablution of the Shiva Linga with milk, honey, ghee, and Gangajal", offerings: "Water, milk, honey, ghee, Bilva leaves, flowers", duration: "45–90 minutes", price: 55, includes: ["Full Rudrabhishek with 11 sacred items", "Sankalpa with your name & gotra", "Video proof", "Vibhuti (sacred ash) shipped"], livestream: true },
      { id: "mangala-aarti", name: "Mangala Aarti Dedication", description: "Pre-dawn lamp-offering ceremony, the most auspicious aarti of the day", offerings: "Incense, flowers, lamps", duration: "15 minutes", price: 30, includes: ["Name announced at 3AM aarti", "Video of the ceremony", "Gangajal + prasad shipped"], livestream: true },
      { id: "shringar-aarti", name: "Shringar Aarti", description: "Evening decoration and lamp-waving ceremony", offerings: "Flowers, lamps", duration: "20 minutes", price: 25, includes: ["Name at evening aarti", "Video proof", "Tilak shipped"], livestream: false },
      { id: "pind-daan", name: "Pind Daan (Ancestor Rites)", description: "Sacred offering of rice balls for the liberation of ancestors", offerings: "Rice balls (pinda), water, sesame", duration: "1–2 hours", price: 80, includes: ["Full Pind Daan on Ganga ghat", "Ancestors' names chanted", "Video", "Certificate of completion"], livestream: false },
    ],
    festivals: ["Maha Shivaratri", "Shravan Mondays", "Dev Deepawali", "Diwali"],
    diaspora: ["USA", "UK", "Canada", "Mauritius"],
    lifeProblems: ["Ancestor liberation", "Sin removal", "Spiritual liberation (moksha)", "Health", "Prosperity"],
    trustNotes: "Managed by Shri Kashi Vishwanath Temple Trust (Varanasi Nagar Nigam)",
    tags: ["shiva", "jyotirlinga", "varanasi", "moksha", "ancestor-rites"],
  },
  {
    slug: "tirupati-balaji",
    id: "H002",
    name: "Tirumala Venkateswara Temple",
    type: "temple",
    location: { city: "Tirupati", state: "Andhra Pradesh", country: "India" },
    primaryFigure: "Lord Venkateswara (Balaji)",
    faith: "Hindu — Vaishnavism",
    icon: "🛕",
    theme: { bg: "bg-yellow-50", nav: "bg-yellow-700", navText: "text-white", accent: "bg-yellow-600", accentText: "text-white", badge: "bg-yellow-100", badgeText: "text-yellow-800" },
    description: "The world's most visited religious site, Lord Venkateswara's abode on the seven sacred hills of Tirumala. It is said that any sincere prayer made here is always answered.",
    significance: "Devotees believe Balaji fulfills any wish made with genuine devotion. The tonsuring (head-shaving) here is one of the most common fulfillment rituals in the world.",
    auspiciousDays: ["Saturdays", "Ekadashi", "Brahmotsavam", "Vaikunta Ekadashi"],
    rituals: [
      { id: "laddu-archana", name: "Laddu Prasad & Archana", description: "Sacred archana in your name with the famous Tirupati laddu", offerings: "Tulsi, flowers, laddu", duration: "1 day", price: 15, includes: ["Archana with your name", "Tirupati laddu shipped internationally", "Name board photo"], livestream: false },
      { id: "abhishek", name: "Panchamrit Abhishek", description: "Sacred bath of the deity with five holy substances", offerings: "Milk, curd, ghee, honey, sugar", duration: "1 day", price: 45, includes: ["Full abhishek ritual", "Video recording", "Prasad + tilak powder shipped"], livestream: true },
      { id: "seegra-darshan", name: "Seegra Darshan Proxy", description: "Priority darshan performed on your behalf", offerings: "Flowers, coconut", duration: "1 day", price: 80, includes: ["Priority darshan in your name", "Video during darshan", "Blessed items shipped"], livestream: true },
      { id: "sahasranama", name: "Sahasranama Archana", description: "Chanting of 1008 divine names of Venkateswara", offerings: "Flowers for each name", duration: "2 hours", price: 30, includes: ["1008 names chanted", "Family names included", "Video proof"], livestream: false },
    ],
    festivals: ["Brahmotsavam (9 days)", "Vaikunta Ekadashi", "Ugadi"],
    diaspora: ["USA", "UK", "Canada", "Malaysia", "Singapore", "Australia"],
    lifeProblems: ["Wish fulfillment", "Marriage", "Children", "Career", "Devotion"],
    trustNotes: "Managed by Tirumala Tirupati Devasthanams (TTD) — government body",
    tags: ["vishnu", "balaji", "venkateswara", "andhra", "wish-fulfillment"],
  },
  {
    slug: "shirdi-sai-baba",
    id: "H003",
    name: "Shri Sai Baba Mandir",
    type: "temple",
    location: { city: "Shirdi", state: "Maharashtra", country: "India" },
    primaryFigure: "Sai Baba of Shirdi",
    faith: "Universal — Hindu & Muslim devotees both",
    icon: "✨",
    theme: { bg: "bg-amber-50", nav: "bg-amber-700", navText: "text-white", accent: "bg-amber-600", accentText: "text-white", badge: "bg-amber-100", badgeText: "text-amber-800" },
    description: "The samadhi shrine of Sai Baba of Shirdi, who embodied 'Sabka Malik Ek' — one God for all. He transcended all religion and is worshipped by Hindus, Muslims, and people of every faith.",
    significance: "Sai Baba promised: 'If you look to me, I look to you.' Thursdays here are considered the most powerful day for wish fulfillment.",
    auspiciousDays: ["Thursdays", "Ram Navami", "Guru Purnima", "Vijayadashami"],
    rituals: [
      { id: "thursday-aarti", name: "Thursday Kakad Aarti", description: "The pre-dawn aarti on Baba's most auspicious day", offerings: "Flowers, incense", duration: "30 minutes", price: 20, includes: ["Name announced at Thursday aarti", "Aarti video", "Udi (sacred ash) shipped"], livestream: true },
      { id: "abhishek", name: "Panchamrit Abhishek", description: "Sacred bathing of Sai Baba's samadhi", offerings: "Milk, rose water, curd", duration: "1 day", price: 35, includes: ["Full abhishek video", "Prasad shipped", "Name board photo"], livestream: false },
      { id: "palki", name: "Palki Procession Dedication", description: "Evening procession with Baba's palanquin", offerings: "Rose petals, incense", duration: "1 hour", price: 25, includes: ["Name in evening palki", "Video of procession", "Udi + prasad"], livestream: false },
    ],
    festivals: ["Guru Purnima", "Ram Navami", "Diwali at Shirdi"],
    diaspora: ["USA", "UK", "Canada", "UAE", "Australia", "New Zealand"],
    lifeProblems: ["Wish fulfillment", "Faith", "Health", "Obstacles", "Family peace"],
    trustNotes: "Managed by Shri Saibaba Sansthan Trust, Shirdi",
    tags: ["sai-baba", "shirdi", "universal", "guru", "thursday"],
  },
  {
    slug: "kedarnath",
    id: "H004",
    name: "Kedarnath Jyotirlinga",
    type: "temple",
    location: { city: "Kedarnath", state: "Uttarakhand", country: "India" },
    primaryFigure: "Lord Shiva (Kedarnath)",
    faith: "Hindu — Shaivism",
    icon: "⛰️",
    theme: { bg: "bg-slate-50", nav: "bg-slate-800", navText: "text-white", accent: "bg-slate-700", accentText: "text-white", badge: "bg-slate-100", badgeText: "text-slate-800" },
    description: "Perched at 3,583 metres in the Himalayas, Kedarnath is one of the 12 Jyotirlingas of Shiva and part of the sacred Char Dham. The ancient stone temple, said to be built by the Pandavas, is open only 6 months a year.",
    significance: "Legend says the Pandavas sought forgiveness here for the war's carnage. A darshan of Kedarnath is said to cleanse all sins of this life and the next.",
    auspiciousDays: ["Mondays", "Shravan month", "Mahashivratri", "Temple opening day (May)"],
    rituals: [
      { id: "rudrabhishek", name: "Rudrabhishek", description: "Sacred ablution with Gangajal and bilva leaves at the ancient Shiva linga", offerings: "Gangajal, milk, bilva", duration: "45 minutes", price: 60, includes: ["Rudrabhishek at the ancient linga", "Video + photos", "Vibhuti shipped"], livestream: false },
      { id: "laghu-rudra", name: "Laghu Rudra Path", description: "Recitation of Rudrashtadhyayi 11 times by multiple priests", offerings: "Flowers, bilva, ghee", duration: "3 hours", price: 120, includes: ["11 priests chanting", "Full ceremony video", "Prasad shipped"], livestream: false },
      { id: "morning-aarti", name: "Morning Aarti Dedication", description: "Name offered at the divine morning aarti", offerings: "Incense, flowers", duration: "30 minutes", price: 40, includes: ["Name at morning aarti", "Aarti video", "Himalayan rudraksha shipped"], livestream: false },
    ],
    festivals: ["Kedarnath Dham opening (May)", "Mahashivratri", "Shravan Mondays"],
    diaspora: ["USA", "UK", "Canada", "UAE"],
    lifeProblems: ["Sin removal", "Moksha", "Health", "Courage", "Spiritual elevation"],
    trustNotes: "Managed by Shri Badrinath-Kedarnath Temple Committee (Uttarakhand government)",
    tags: ["shiva", "jyotirlinga", "char-dham", "himalayas", "kedarnath"],
  },
  {
    slug: "vaishno-devi",
    id: "H005",
    name: "Vaishno Devi Shrine",
    type: "shrine",
    location: { city: "Katra", state: "Jammu & Kashmir", country: "India" },
    primaryFigure: "Mata Vaishno Devi (Shakti)",
    faith: "Hindu — Shaktism",
    icon: "🏔️",
    theme: { bg: "bg-red-50", nav: "bg-red-800", navText: "text-white", accent: "bg-red-700", accentText: "text-white", badge: "bg-red-100", badgeText: "text-red-800" },
    description: "Mata Vaishno Devi's cave shrine in the Trikuta Mountains is one of the most visited pilgrimage sites in India. The 14-km trek to the cave shrine is itself considered a form of devotion.",
    significance: "Mata is believed to call devotees when the time is right. 'Jai Mata Di' is the battle cry of those who have felt her call.",
    auspiciousDays: ["Navratri (twice a year)", "Ashtami", "Purnima", "Saturdays"],
    rituals: [
      { id: "darshan-proxy", name: "Darshan Proxy Visit", description: "Our representative completes the full trek and cave darshan in your name", offerings: "Chunri, coconut, flowers", duration: "2 days (trek)", price: 50, includes: ["Full trek + cave darshan", "Video during pindies darshan", "Chunri & prasad shipped"], livestream: false },
      { id: "chunri", name: "Chunri Chadhana", description: "Sacred red cloth offered at Mata's feet", offerings: "Red chunri", duration: "1 day", price: 30, includes: ["Chunri offered in your name", "Photo with your name board", "Blessed vermilion shipped"], livestream: false },
      { id: "navratri-puja", name: "Navratri Special Puja", description: "Elaborate puja performed during the sacred nine nights", offerings: "Full puja samagri", duration: "1 day", price: 90, includes: ["Special Navratri rituals", "Video", "Full prasad kit shipped"], livestream: false },
    ],
    festivals: ["Navratri (spring & autumn)", "Diwali"],
    diaspora: ["USA", "UK", "Canada", "UAE", "Australia"],
    lifeProblems: ["Wish fulfillment", "Protection", "Fertility", "Marriage", "Recovery from illness"],
    trustNotes: "Managed by Shri Mata Vaishno Devi Shrine Board (J&K government)",
    tags: ["shakti", "mata", "devi", "navratri", "cave-shrine"],
  },
  {
    slug: "mahakaleshwar",
    id: "H006",
    name: "Mahakaleshwar Jyotirlinga",
    type: "temple",
    location: { city: "Ujjain", state: "Madhya Pradesh", country: "India" },
    primaryFigure: "Mahakal (Lord Shiva)",
    faith: "Hindu — Shaivism",
    icon: "🔱",
    theme: { bg: "bg-zinc-50", nav: "bg-zinc-800", navText: "text-white", accent: "bg-zinc-700", accentText: "text-white", badge: "bg-zinc-100", badgeText: "text-zinc-800" },
    description: "The only south-facing (Dakshinamukhi) Jyotirlinga — Mahakal is the lord of time and death itself. The legendary Bhasma Aarti at 4 AM, where the deity is smeared with sacred ash, is one of the rarest rituals in Hindu worship.",
    significance: "Worshipping Mahakal is said to free devotees from the fear of death and the cycle of time itself.",
    auspiciousDays: ["Mondays", "Mahashivratri", "Shravan Mondays", "Kumbh Mela"],
    rituals: [
      { id: "bhasma-aarti", name: "4AM Bhasma Aarti Dedication", description: "The legendary pre-dawn aarti where deity is anointed with sacred ash — open only to limited devotees", offerings: "Sacred bhasma (ash)", duration: "1 hour", price: 55, includes: ["Name at legendary Bhasma Aarti", "Full aarti video", "Sacred bhasma (ash) shipped"], livestream: false },
      { id: "rudrabhishek", name: "Rudrabhishek", description: "Sacred abhishek at the Dakshinamukhi Shiva linga", offerings: "Milk, honey, ghee, bilva", duration: "1 hour", price: 70, includes: ["Full rudrabhishek", "Video", "Prasad + rudraksha"], livestream: false },
      { id: "naivedya", name: "Naivedya Offering", description: "Food offering to Mahakal in your name", offerings: "Sweets, fruits", duration: "30 minutes", price: 25, includes: ["Offering in your name", "Photo proof", "Blessed tilak"], livestream: false },
    ],
    festivals: ["Mahashivratri", "Shravan Mondays", "Kumbh Mela (every 12 years)"],
    diaspora: ["USA", "UK", "Canada"],
    lifeProblems: ["Fear of death", "Time/destiny", "Enemies", "Spiritual power"],
    trustNotes: "Managed by Mahakaleshwar Temple Committee, Ujjain (MP government)",
    tags: ["shiva", "jyotirlinga", "ujjain", "bhasma-aarti", "dakshinamukhi"],
  },
  {
    slug: "jagannath-puri",
    id: "H007",
    name: "Jagannath Temple, Puri",
    type: "temple",
    location: { city: "Puri", state: "Odisha", country: "India" },
    primaryFigure: "Lord Jagannath (Vishnu)",
    faith: "Hindu — Vaishnavism",
    icon: "🎪",
    theme: { bg: "bg-orange-50", nav: "bg-orange-700", navText: "text-white", accent: "bg-orange-600", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-800" },
    description: "Lord Jagannath — Lord of the Universe — presides over one of India's four sacred dhams at Puri. The annual Rath Yatra chariot festival is one of the world's largest religious processions, drawing millions.",
    significance: "The Mahaprasad (food offered to Jagannath) is considered so sacred that even Brahma is said to desire it. There is no caste distinction in his kitchen.",
    auspiciousDays: ["Rath Yatra", "Ekadashi", "Purnima", "Snana Purnima"],
    rituals: [
      { id: "mahaprasad", name: "Mahaprasad Offering", description: "Sacred food offering to Lord Jagannath, blessed and shipped", offerings: "56 varieties of food (Chhappan Bhog)", duration: "1 day", price: 30, includes: ["Offering in your name", "Mahaprasad shipped", "Photo proof"], livestream: false },
      { id: "aarti-dedication", name: "Sandhya Aarti Dedication", description: "Evening lamp ceremony at the 12th-century temple", offerings: "Lamps, flowers", duration: "30 minutes", price: 25, includes: ["Name at sandhya aarti", "Video", "Tilak shipped"], livestream: false },
    ],
    festivals: ["Rath Yatra (June/July)", "Snana Purnima", "Diwali"],
    diaspora: ["USA", "UK", "Odia diaspora globally"],
    lifeProblems: ["Devotion", "Ancestor blessings", "Liberation", "Equality"],
    trustNotes: "Administered by Sri Jagannath Temple Administration (Odisha government)",
    tags: ["vishnu", "jagannath", "rath-yatra", "char-dham", "puri"],
  },
  {
    slug: "badrinath",
    id: "H008",
    name: "Shri Badrinath Temple",
    type: "temple",
    location: { city: "Badrinath", state: "Uttarakhand", country: "India" },
    primaryFigure: "Vishnu (Badrinarayan)",
    faith: "Hindu — Vaishnavism",
    icon: "🏔️",
    theme: { bg: "bg-blue-50", nav: "bg-blue-800", navText: "text-white", accent: "bg-blue-700", accentText: "text-white", badge: "bg-blue-100", badgeText: "text-blue-800" },
    description: "The most important of the four Char Dham pilgrimage sites, Badrinath sits at 3,133 metres in the Garhwal Himalayas on the banks of the Alaknanda river. Open only May–November.",
    significance: "'He who chants the name of Badri shall be liberated' — Skanda Purana. One of Adi Shankaracharya's most sacred establishments.",
    auspiciousDays: ["Temple opening day (May)", "Ekadashi", "Makar Sankranti"],
    rituals: [
      { id: "abhishek", name: "Brahma Abhishek", description: "Early morning abhishek of Badrinarayan", offerings: "Tapt Kund (hot spring) water, flowers, yogurt", duration: "30 minutes", price: 45, includes: ["Abhishek in your name", "Video", "Char Dham prasad shipped"], livestream: false },
      { id: "puja", name: "Sahastranam Puja", description: "1000 names of Vishnu chanted before the deity", offerings: "Tulsi, flowers", duration: "2 hours", price: 60, includes: ["Full puja", "Video", "Prasad"], livestream: false },
    ],
    festivals: ["Char Dham Yatra season (May–Nov)", "Badri Kedar Festival"],
    diaspora: ["USA", "UK", "Canada", "Nepal"],
    lifeProblems: ["Spiritual merit", "Pilgrimage fulfillment", "Moksha"],
    trustNotes: "Managed by Shri Badrinath-Kedarnath Temple Committee (Uttarakhand government)",
    tags: ["vishnu", "char-dham", "himalayas", "badrinath", "vaishnavism"],
  },
  {
    slug: "dwarka",
    id: "H009",
    name: "Dwarkadhish Temple",
    type: "temple",
    location: { city: "Dwarka", state: "Gujarat", country: "India" },
    primaryFigure: "Lord Krishna (Dwarkadhish)",
    faith: "Hindu — Vaishnavism",
    icon: "🦚",
    theme: { bg: "bg-indigo-50", nav: "bg-indigo-800", navText: "text-white", accent: "bg-indigo-700", accentText: "text-white", badge: "bg-indigo-100", badgeText: "text-indigo-800" },
    description: "One of the four sacred Char Dhams, Dwarka is the legendary kingdom of Lord Krishna. The Dwarkadhish temple is said to stand on the original palace of Krishna, with the sea that submerged his city below.",
    significance: "Dwarka is the westernmost of the four dhams and represents the twilight of Krishna's earthly life — the most bittersweet of all pilgrimage stops.",
    auspiciousDays: ["Janmashtami", "Ekadashi", "Purnima", "Fridays"],
    rituals: [
      { id: "darshan-aarti", name: "Darshan & Aarti", description: "Five daily worship services (aarti) in the ancient 2500-year-old temple", offerings: "Flowers, sweets, tulsi", duration: "30 minutes", price: 30, includes: ["Aarti in your name", "Video", "Prasad shipped"], livestream: false },
      { id: "abhishek", name: "Dwarka Abhishek", description: "Sacred bathing of Lord Dwarkadhish", offerings: "Panchamrit", duration: "1 hour", price: 55, includes: ["Full abhishek", "Video", "Prasad + peacock feather blessed item"], livestream: false },
    ],
    festivals: ["Janmashtami", "Holi", "Annakut"],
    diaspora: ["USA", "UK", "Canada", "Kenya", "Fiji"],
    lifeProblems: ["Devotion", "Family welfare", "Courage", "Love"],
    trustNotes: null,
    tags: ["krishna", "char-dham", "gujarat", "dwarka", "vaishnavism"],
  },

  // ── SIKH GURDWARAS ─────────────────────────────────────────────────────────
  {
    slug: "golden-temple",
    id: "S001",
    name: "Harmandir Sahib (Sri Darbar Sahib)",
    type: "gurdwara",
    location: { city: "Amritsar", state: "Punjab", country: "India" },
    primaryFigure: "Guru Arjan Dev Ji (compiled Adi Granth here)",
    faith: "Sikh",
    icon: "🌟",
    theme: { bg: "bg-amber-50", nav: "bg-blue-900", navText: "text-white", accent: "bg-blue-800", accentText: "text-white", badge: "bg-blue-100", badgeText: "text-blue-900" },
    description: "The holiest shrine in Sikhism, Sri Harmandir Sahib shines in gold at the center of Amrit Sarovar (nectar pool) in Amritsar. The Akhand Path (non-stop Gurbani) and free langar (community kitchen) run 24 hours a day, every day — never stopping.",
    significance: "Built to be open on all four sides, welcoming people of every faith. The Guru Granth Sahib here is believed to be the living Guru, not a book.",
    auspiciousDays: ["Gurpurab (Guru Nanak, Guru Gobind Singh)", "Vaisakhi", "Every day"],
    rituals: [
      { id: "ardas", name: "Ardas on Your Behalf", description: "Personal prayer offered at Sri Akal Takht in your name", offerings: "Karah Prasad (sacred halwa)", duration: "1 day", price: 20, includes: ["Personal Ardas with full family names", "Video of Ardas at the shrine", "Hukamnama (divine message) shared"], livestream: true },
      { id: "langar-seva", name: "Langar Dedication (50 Souls)", description: "Sponsor the free community meal in your family's name", offerings: "Langar ingredients", duration: "1 day", price: 40, includes: ["Langar served in your family's name", "Photo proof", "Certificate of seva"], livestream: false },
      { id: "hukamnama", name: "Daily Hukamnama + Ardas", description: "Morning divine message (Hukamnama) recited for your intention", offerings: "null", duration: "1 day", price: 15, includes: ["Morning Hukamnama for you", "Audio on WhatsApp", "Your name in daily prayer"], livestream: false },
      { id: "akhand-path", name: "Akhand Path (48 hours)", description: "48-hour non-stop recitation of the complete Guru Granth Sahib", offerings: "null", duration: "48 hours", price: 150, includes: ["48-hour scripture reading", "Family names throughout", "Certificate + video highlights"], livestream: true },
    ],
    festivals: ["Vaisakhi", "Guru Nanak Jayanti", "Diwali at Amritsar (Bandi Chhor Divas)", "Hola Mohalla"],
    diaspora: ["Canada (~500k)", "UK (~450k)", "USA (~300k)", "Australia", "Malaysia"],
    lifeProblems: ["Spiritual guidance", "Courage", "Community (seva)", "Gratitude", "Family blessings"],
    trustNotes: "Managed by Shiromani Gurdwara Parbandhak Committee (SGPC)",
    tags: ["sikh", "gurdwara", "amritsar", "golden-temple", "ardas", "langar"],
  },
  {
    slug: "hemkund-sahib",
    id: "S002",
    name: "Hemkund Sahib",
    type: "gurdwara",
    location: { city: "Chamoli District", state: "Uttarakhand", country: "India" },
    primaryFigure: "Guru Gobind Singh Ji",
    faith: "Sikh",
    icon: "🏔️",
    theme: { bg: "bg-sky-50", nav: "bg-blue-900", navText: "text-white", accent: "bg-blue-800", accentText: "text-white", badge: "bg-sky-100", badgeText: "text-sky-900" },
    description: "Perched at 4,329 metres beside a glacial lake in the Himalayas, Hemkund Sahib is where Guru Gobind Singh Ji meditated in a previous life. The high-altitude trek is one of the most demanding in Sikhism — let us carry your prayers there.",
    significance: "Guru Gobind Singh wrote in the Dasam Granth that he meditated at 'Hem Kunt Parwat' — this place. The glacial lake is considered sacred beyond measure.",
    auspiciousDays: ["Open June–October", "Gurpurab of Guru Gobind Singh"],
    rituals: [
      { id: "ardas-sarovar", name: "Ardas at the Sacred Sarovar", description: "Prayer at the glacial lake shrine after the high-altitude trek", offerings: "Karah Prasad", duration: "1 trek day", price: 25, includes: ["Ardas at the lake shrine", "Trek video", "Sacred jal (glacier water) shipped"], livestream: false },
      { id: "ishnaan", name: "Sacred Ishnaan (Glacial Bath) Proxy", description: "Ritual bath in the freezing glacial lake performed in your intention", offerings: "null", duration: "1 day", price: 30, includes: ["Ishnaan performed in your name", "Video at the lake", "Blessed water + prasad shipped"], livestream: false },
    ],
    festivals: ["Seasonal opening ceremony (June)"],
    diaspora: ["Canada", "UK", "USA", "Australia"],
    lifeProblems: ["Deep spiritual merit", "Blessings of the Guru", "Health", "Surrender"],
    trustNotes: "Managed by SGPC",
    tags: ["sikh", "gurdwara", "himalayas", "guru-gobind-singh", "glacial-lake"],
  },

  // ── DARGAHS & SUFI SHRINES ─────────────────────────────────────────────────
  {
    slug: "ajmer-sharif",
    id: "M001",
    name: "Dargah Khwaja Moinuddin Chishti",
    type: "dargah",
    location: { city: "Ajmer", state: "Rajasthan", country: "India" },
    primaryFigure: "Khwaja Moinuddin Chishti (Gharib Nawaz)",
    faith: "Islam (Chishti Sufi) — open to all",
    icon: "🌙",
    theme: { bg: "bg-green-50", nav: "bg-green-800", navText: "text-white", accent: "bg-green-700", accentText: "text-white", badge: "bg-green-100", badgeText: "text-green-800" },
    description: "The most visited dargah in the world — the sacred resting place of Gharib Nawaz, 'Helper of the Poor'. Khwaja Sahib's mercy transcends all boundaries of faith, caste and status. Emperors and beggars alike have knelt here.",
    significance: "Akbar himself walked barefoot from Agra to Ajmer in gratitude for the birth of his son after praying here. The Urs (death anniversary) draws 3 million in 6 days.",
    auspiciousDays: ["Thursdays", "Urs festival (6th Rajab)", "Shab-e-Barat", "Friday after Jumma"],
    rituals: [
      { id: "chaddar", name: "Chaddar Offering", description: "Sacred embroidered cloth offered at the mazaar of Gharib Nawaz", offerings: "Chaddar (cloth), rose petals, attar", duration: "1 day", price: 35, includes: ["Premium chaddar placed at mazaar", "Fatiha recited in your name", "Video + photos", "Tabaruk (blessed sweets) shipped"], livestream: false },
      { id: "qawwali", name: "Thursday Night Qawwali Dedication", description: "Your mannat (wish) announced during the sacred Thursday night qawwali", offerings: "Rose petals", duration: "1 night", price: 25, includes: ["Name at Thursday qawwali", "Audio/video of dedication", "Blessed rose petals shipped"], livestream: false },
      { id: "fatiha-dua", name: "Fatiha & Personal Dua", description: "Fatiha (opening chapter) recited and personal dua made at the mazaar", offerings: "Flowers", duration: "1 day", price: 20, includes: ["Fatiha at the shrine", "Personal dua with your name", "Video proof"], livestream: false },
      { id: "urs-booking", name: "Urs Festival Special Booking", description: "Participation in the grand annual death-anniversary celebrations", offerings: "Chaddar, flowers, dates", duration: "Urs days", price: 80, includes: ["Urs ritual participation", "Chaddar + flowers", "Full ceremony video", "Blessed items shipped"], livestream: false },
    ],
    festivals: ["Urs of Gharib Nawaz (6 days in Rajab)", "Shab-e-Barat", "Eid"],
    diaspora: ["Pakistan", "Bangladesh", "India (Rajasthani diaspora)", "UK", "UAE"],
    lifeProblems: ["Mannat (wish fulfillment)", "Healing", "Spiritual solace", "Poverty relief", "Marriage"],
    trustNotes: "Managed by Dargah Khwaja Saheb Trust (Ministry of Minority Affairs, India)",
    tags: ["sufi", "chishti", "dargah", "ajmer", "mannat", "qalandari"],
  },
  {
    slug: "data-darbar",
    id: "M002",
    name: "Data Darbar Shrine",
    type: "dargah",
    location: { city: "Lahore", state: "Punjab", country: "Pakistan" },
    primaryFigure: "Hazrat Ali Hujwiri (Data Ganj Bakhsh)",
    faith: "Islam (Chishti Sufi) — open to all",
    icon: "⭐",
    theme: { bg: "bg-emerald-50", nav: "bg-emerald-800", navText: "text-white", accent: "bg-emerald-700", accentText: "text-white", badge: "bg-emerald-100", badgeText: "text-emerald-800" },
    description: "Data Ganj Bakhsh — 'Giver of Endless Treasures' — the oldest and most revered Sufi shrine in Pakistan. His 11th-century text Kashf al-Mahjub is the first Sufi book in Persian. Thursday nights here are legendary across South Asia.",
    significance: "Khwaja Moinuddin Chishti himself visited this shrine and said: 'Ganj Bakhsh is the light of both worlds, the perfect murshid for the imperfect, the guide for those who have arrived.'",
    auspiciousDays: ["Thursdays", "Urs festival", "Shab-e-Qadr"],
    rituals: [
      { id: "chadar", name: "Chadar Offering at Data Sahib's Mazaar", description: "Sacred cloth offered at the blessed mazaar", offerings: "Chadar, rose petals, attar", duration: "1 day", price: 30, includes: ["Chadar placed at Data Sahib's mazaar", "Fatiha in your name", "Video proof", "Tabaruk shipped"], livestream: false },
      { id: "mannat", name: "Mannat Dedication", description: "Your specific wish presented at the mazaar with dua", offerings: "Flowers, incense", duration: "1 day", price: 25, includes: ["Wish presented at shrine", "Dua on your behalf", "Photo proof"], livestream: false },
      { id: "thursday-mehfil", name: "Thursday Night Mehfil", description: "Devotional gathering every Thursday night", offerings: "Rose petals", duration: "1 night", price: 20, includes: ["Name in Thursday gathering", "Video of mehfil", "Blessed rose water shipped"], livestream: false },
    ],
    festivals: ["Annual Urs", "Shab-e-Barat", "Eid ul-Fitr"],
    diaspora: ["Pakistani diaspora UK", "Canada", "UAE", "USA"],
    lifeProblems: ["Wish fulfillment", "Spiritual knowledge", "Blessings", "Marriage", "Career"],
    trustNotes: "Managed by Auqaf Department, Punjab, Pakistan",
    tags: ["sufi", "pakistan", "lahore", "data-sahib", "mannat"],
  },
  {
    slug: "nizamuddin-dargah",
    id: "M003",
    name: "Hazrat Nizamuddin Dargah",
    type: "dargah",
    location: { city: "New Delhi", state: "Delhi", country: "India" },
    primaryFigure: "Hazrat Nizamuddin Auliya",
    faith: "Islam (Chishti Sufi) — open to all",
    icon: "🕌",
    theme: { bg: "bg-teal-50", nav: "bg-teal-800", navText: "text-white", accent: "bg-teal-700", accentText: "text-white", badge: "bg-teal-100", badgeText: "text-teal-800" },
    description: "The dargah of Hazrat Nizamuddin Auliya, the great Chishti saint of Delhi, has been a center of spiritual life for 700 years. The Thursday evening qawwali has run unbroken since the 14th century. Amir Khusrow's tomb is also here.",
    significance: "Nizamuddin's teaching was love — 'Love is God and God is Love'. His disciple Amir Khusrow gave India the sitar and qawwali. This is the beating heart of Delhi's spiritual life.",
    auspiciousDays: ["Thursdays", "Urs", "Basant Panchami (unique celebration here)"],
    rituals: [
      { id: "qawwali-dedication", name: "Thursday Qawwali Dedication", description: "700-year-old tradition — name entered in Thursday's qawwali", offerings: "Rose petals, incense", duration: "1 night", price: 20, includes: ["Name in Thursday qawwali", "Video recording", "Blessed flowers shipped"], livestream: false },
      { id: "chadar-flowers", name: "Chadar & Flowers", description: "Chadar and rose offering at the mazaar", offerings: "Chadar, roses", duration: "1 day", price: 25, includes: ["Chadar + rose offering", "Fatiha recited", "Photo with dedication"], livestream: false },
      { id: "fatiha", name: "Fatiha Khwani", description: "Fatiha recited at the mazaar for your intention", offerings: "Flowers", duration: "1 day", price: 15, includes: ["Fatiha for your intention", "Video proof", "Blessed tabaruk"], livestream: false },
    ],
    festivals: ["Urs of Nizamuddin Auliya", "Urs of Amir Khusrow", "Basant (unique yellow flower festival)"],
    diaspora: ["India (Delhi/UP diaspora)", "Pakistan", "Bangladesh", "UK"],
    lifeProblems: ["Spiritual love", "Healing", "Wish fulfillment", "Artistic blessings"],
    trustNotes: null,
    tags: ["sufi", "chishti", "delhi", "qawwali", "amir-khusrow"],
  },

  // ── CHURCHES & CHRISTIAN SHRINES ───────────────────────────────────────────
  {
    slug: "velankanni",
    id: "C001",
    name: "Basilica of Our Lady of Good Health",
    type: "church",
    location: { city: "Velankanni", state: "Tamil Nadu", country: "India" },
    primaryFigure: "Virgin Mary (Our Lady of Good Health / Arokia Matha)",
    faith: "Christian — Roman Catholic",
    icon: "⛪",
    theme: { bg: "bg-sky-50", nav: "bg-sky-800", navText: "text-white", accent: "bg-sky-700", accentText: "text-white", badge: "bg-sky-100", badgeText: "text-sky-900" },
    description: "Called the 'Lourdes of the East', Our Lady of Velankanni has healed the sick and comforted the suffering since the 16th century. The September feast draws over a million pilgrims of all faiths — a testament to her universal grace.",
    significance: "Three miraculous apparitions of Mary are recorded here. The fishermen who built the first chapel survived a storm after praying to her — the sea itself bore witness.",
    auspiciousDays: ["Fridays", "September feast (Aug 29–Sep 8)", "Christmas", "Good Friday"],
    rituals: [
      { id: "candle", name: "Candle Lighting & Prayer", description: "Candle lit before Our Lady with your intention", offerings: "Candle, flowers", duration: "1 day", price: 15, includes: ["Candle lit at Our Lady's feet", "Your intention prayed", "Photo of lit candle", "Blessed medal shipped"], livestream: false },
      { id: "novena", name: "9-Day Novena Dedication", description: "Your name and intention in the 9-day novena prayers", offerings: "Candles, flowers", duration: "9 days", price: 25, includes: ["Name in 9-day novena", "Daily WhatsApp updates", "Novena booklet + medal shipped"], livestream: false },
      { id: "mass-offering", name: "Holy Mass Offering", description: "Mass offered for your intention at the Basilica", offerings: "Candles", duration: "1 hour", price: 35, includes: ["Mass offered for your intention", "Mass card", "Video of Mass", "Blessed items shipped"], livestream: false },
      { id: "votive", name: "Votive Thanksgiving Offering", description: "Thanksgiving offering placed at the shrine", offerings: "Votive lamp, flowers", duration: "1 day", price: 20, includes: ["Thanksgiving offering in your name", "Photo", "Blessed rosary shipped"], livestream: false },
    ],
    festivals: ["Annual Feast (Aug 29–Sep 8)", "Christmas", "Good Friday", "Assumption of Mary (Aug 15)"],
    diaspora: ["Tamil diaspora Malaysia, Singapore, UK, UAE", "Goan diaspora"],
    lifeProblems: ["Healing", "Miracles", "Family safety at sea", "Gratitude", "Children"],
    trustNotes: "Managed by the Diocese of Tanjore",
    tags: ["mary", "catholic", "velankanni", "miracle", "healing"],
  },
  {
    slug: "bom-jesus-goa",
    id: "C002",
    name: "Basilica of Bom Jesus, Goa",
    type: "church",
    location: { city: "Old Goa", state: "Goa", country: "India" },
    primaryFigure: "St. Francis Xavier",
    faith: "Christian — Roman Catholic",
    icon: "✝️",
    theme: { bg: "bg-blue-50", nav: "bg-blue-900", navText: "text-white", accent: "bg-blue-800", accentText: "text-white", badge: "bg-blue-100", badgeText: "text-blue-900" },
    description: "A UNESCO World Heritage Site, this 1605 baroque basilica houses the incorrupt body of St. Francis Xavier — the 'Apostle of the East' who evangelized across India, Southeast Asia and Japan. His body has not decayed in over 450 years.",
    significance: "The Exposition of St. Francis Xavier's relics (every 10 years) is one of the world's largest Catholic gatherings. His intercession is sought for healing and mission.",
    auspiciousDays: ["Feast of St. Francis Xavier (Dec 3)", "Christmas", "Sundays"],
    rituals: [
      { id: "mass", name: "Holy Mass at the Basilica", description: "Mass offered at the feet of St. Francis Xavier", offerings: "Candles, flowers", duration: "1 hour", price: 20, includes: ["Mass for your intention", "Mass card", "Video", "Blessed medal shipped"], livestream: false },
      { id: "candle-relic", name: "Candle at the Relic Chapel", description: "Candle lit before the incorrupt relics of St. Francis Xavier", offerings: "Candle", duration: "1 day", price: 15, includes: ["Candle lit before relics", "Photo proof", "Blessed medal"], livestream: false },
    ],
    festivals: ["Feast of St. Francis Xavier (Dec 3)", "Christmas", "Easter"],
    diaspora: ["Goan diaspora in UK, Portugal, UAE, Australia"],
    lifeProblems: ["Healing", "Mission", "Faith", "Forgiveness"],
    trustNotes: "Managed by the Archdiocese of Goa and Daman",
    tags: ["catholic", "goa", "st-francis-xavier", "relic", "heritage"],
  },

  // ── BUDDHIST ───────────────────────────────────────────────────────────────
  {
    slug: "mahabodhi-bodhgaya",
    id: "B001",
    name: "Mahabodhi Temple",
    type: "monastery",
    location: { city: "Bodh Gaya", state: "Bihar", country: "India" },
    primaryFigure: "Siddhartha Gautama (the Buddha)",
    faith: "Buddhist",
    icon: "☸️",
    theme: { bg: "bg-yellow-50", nav: "bg-yellow-800", navText: "text-white", accent: "bg-yellow-700", accentText: "text-white", badge: "bg-yellow-100", badgeText: "text-yellow-900" },
    description: "The most sacred site in Buddhism — where Siddhartha Gautama attained enlightenment under the Bodhi tree. The current Bodhi tree is a direct descendant of the original. A UNESCO World Heritage Site visited by Buddhists from every tradition worldwide.",
    significance: "The Diamond Throne (Vajrasana) on which Buddha sat is believed to be the center of the earth and the navel of the universe. Meditation here is said to carry extraordinary power.",
    auspiciousDays: ["Buddha Purnima (May)", "Vassa (monsoon retreat)", "Loy Krathong"],
    rituals: [
      { id: "pradakshina", name: "Pradakshina (Circumambulation)", description: "Ritual walk around the Bodhi tree and main shrine with prayers", offerings: "Flowers, candles, incense", duration: "30 minutes", price: 20, includes: ["Pradakshina in your name", "Video at Bodhi tree", "Blessed Bodhi leaf shipped"], livestream: false },
      { id: "lamp-offering", name: "Oil Lamp Offering", description: "Lamp lit at the Bodhi tree for your merit and intention", offerings: "Oil lamp, flowers", duration: "1 day", price: 15, includes: ["Lamp lit at Bodhi tree", "Photo proof", "Blessed items shipped"], livestream: false },
      { id: "meditation-dedication", name: "Meditation Dedication", description: "Monk meditates at the Vajrasana for one hour dedicating merit to you", offerings: "null", duration: "1 hour", price: 35, includes: ["1-hour meditation at Diamond Throne in your name", "Video", "Merit certificate"], livestream: false },
    ],
    festivals: ["Buddha Purnima", "Bodhi Day (Dec 8 for Zen)", "Dalai Lama teachings (January)"],
    diaspora: ["Sri Lanka", "Myanmar", "Thailand", "Japan", "Korea", "Tibet", "Western Buddhists globally"],
    lifeProblems: ["Enlightenment", "Merit accumulation", "Peace", "Ancestor merit", "Suffering relief"],
    trustNotes: "UNESCO World Heritage Site; managed by Bodh Gaya Temple Management Committee",
    tags: ["buddhism", "buddha", "bodhi-tree", "enlightenment", "meditation", "heritage"],
  },

  // ── JAIN ──────────────────────────────────────────────────────────────────
  {
    slug: "palitana",
    id: "J001",
    name: "Palitana Temples (Shatrunjaya Hill)",
    type: "temple",
    location: { city: "Palitana", state: "Gujarat", country: "India" },
    primaryFigure: "Shri Adinath (Rishabhanatha) — first Jain Tirthankara",
    faith: "Jain",
    icon: "🕊️",
    theme: { bg: "bg-white", nav: "bg-stone-800", navText: "text-white", accent: "bg-stone-700", accentText: "text-white", badge: "bg-stone-100", badgeText: "text-stone-800" },
    description: "The holiest pilgrimage site in Jainism — 900+ marble temples crown the sacred Shatrunjaya Hill, visible for miles. The climb of 3,800 steps is itself a form of devotion. No overnight stay allowed on the hill — it belongs to the gods alone.",
    significance: "The hill is so sacred that over 23 crore Jains are said to have attained liberation here. Every Jain aspires to visit at least once.",
    auspiciousDays: ["Paryushana", "Mahavir Jayanti", "Kartik Purnima", "Phalgun Purnima"],
    rituals: [
      { id: "snatra-puja", name: "Snatra Puja (Abhishek of Adinath)", description: "Bathing the Jain deity with milk and saffron water", offerings: "Milk, saffron water, sandalwood", duration: "30 minutes", price: 35, includes: ["Snatra Puja at main Adinath temple", "Video", "Blessed saffron shipped"], livestream: false },
      { id: "navkar-mantra", name: "Navkar Mantra Recitation", description: "108 recitations of the universal Jain prayer in your name", offerings: "null", duration: "1 hour", price: 20, includes: ["108 Navkar Mantra in your name", "Video", "Rudraksha/Jain prayer beads shipped"], livestream: false },
    ],
    festivals: ["Paryushana (Aug/Sep)", "Mahavir Jayanti (Mar/Apr)", "Diwali (Jain New Year)"],
    diaspora: ["USA (Jain community)", "UK", "East Africa (Kenyan Jains)", "Canada"],
    lifeProblems: ["Purity", "Salvation (moksha)", "Non-violence", "Karmic cleansing"],
    trustNotes: null,
    tags: ["jain", "tirthankara", "gujarat", "shatrunjaya", "liberation"],
  },

  // ── GURU / ASHRAM PAGES ───────────────────────────────────────────────────
  {
    slug: "osho-ashram",
    id: "G001",
    name: "Osho International Meditation Resort",
    type: "ashram",
    location: { city: "Pune", state: "Maharashtra", country: "India" },
    primaryFigure: "Osho (Bhagwan Shree Rajneesh)",
    faith: "Universal — no religion required",
    icon: "🌸",
    theme: { bg: "bg-purple-50", nav: "bg-purple-900", navText: "text-white", accent: "bg-purple-700", accentText: "text-white", badge: "bg-purple-100", badgeText: "text-purple-900" },
    description: "The meditation resort where Osho lived and taught — now one of the world's largest meditation centers. Osho's teachings synthesized Zen, Sufism, Tantra, yoga, and modern psychology into a radical vision of individual awakening. His samadhi is here.",
    significance: "Osho said: 'The moment you accept yourself, you become beautiful.' His 3,000+ talks have been translated into 60+ languages. The campus runs 100+ meditation methods daily.",
    auspiciousDays: ["Osho's Enlightenment Day (March 21)", "Osho Mahaparinirvana Day (January 19)", "Daily"],
    rituals: [
      { id: "samadhi-meditation", name: "Meditation at Osho's Samadhi", description: "Silent meditation session at Osho's resting place in your name", offerings: "null", duration: "1 hour", price: 25, includes: ["1-hour meditation at samadhi in your name", "Video of the meditation hall", "Signed photo of the session"], livestream: false },
      { id: "dynamic-meditation", name: "Dynamic Meditation Dedication", description: "The famous Osho morning meditation, one session dedicated in your name", offerings: "null", duration: "1 hour", price: 20, includes: ["Dynamic Meditation in your name", "Video of the session", "Osho meditation music CD shipped"], livestream: false },
    ],
    festivals: ["Osho Enlightenment Day (March 21)", "Celebration of Osho's talks anniversary"],
    diaspora: ["Germany", "USA", "Japan", "Israel", "Netherlands", "Worldwide"],
    lifeProblems: ["Inner freedom", "Creativity", "Love & relationships", "Existential questions", "Meditation"],
    trustNotes: "Run by Osho International Foundation (private, non-religious)",
    tags: ["osho", "meditation", "pune", "consciousness", "universal", "rajneesh"],
  },
  {
    slug: "amma-amritapuri",
    id: "G002",
    name: "Amritapuri Ashram (Mata Amritanandamayi)",
    type: "ashram",
    location: { city: "Kollam", state: "Kerala", country: "India" },
    primaryFigure: "Mata Amritanandamayi (Amma)",
    faith: "Hindu — Universal",
    icon: "💛",
    theme: { bg: "bg-pink-50", nav: "bg-pink-800", navText: "text-white", accent: "bg-pink-700", accentText: "text-white", badge: "bg-pink-100", badgeText: "text-pink-900" },
    description: "The home ashram of Mata Amritanandamayi — 'Amma' (Mother) — the hugging saint who has embraced over 40 million people worldwide. Her ashram on a Kerala backwater island is a center of devotion, service, and spiritual inquiry.",
    significance: "Amma says: 'My religion is love.' She has given individual hugs to more humans than any other person in history. Her charities operate hospitals and disaster relief globally.",
    auspiciousDays: ["Amma's birthday (Karkidakam, Sept)", "Devi Bhava nights", "Shivaratri"],
    rituals: [
      { id: "virtual-darshan-dedication", name: "Darshan Dedication", description: "Prayer and meditation dedicated to you during Amma's darshan programs", offerings: "Flowers", duration: "1 day", price: 20, includes: ["Dedicated prayer during darshan", "Video of ashram", "Blessed prasad from Amma's kitchen shipped"], livestream: true },
      { id: "devi-bhava", name: "Devi Bhava Night Dedication", description: "During Amma's Devi Bhava — when she embodies the Divine Mother — your name is offered", offerings: "Flowers, coconut", duration: "1 night", price: 35, includes: ["Name at Devi Bhava", "Video of the event", "Kumkum + prasad shipped"], livestream: false },
    ],
    festivals: ["Amma's Birthday", "Devi Bhava programs", "Onam", "Shivaratri"],
    diaspora: ["USA", "Europe", "Japan", "Australia", "Global Amma following"],
    lifeProblems: ["Love", "Compassion", "Healing", "Grief", "Surrender"],
    trustNotes: "Run by Mata Amritanandamayi Math (registered charitable trust)",
    tags: ["amma", "hugging-saint", "kerala", "devi", "universal-love"],
  },
  {
    slug: "iskcon-vrindavan",
    id: "G003",
    name: "ISKCON Vrindavan (Krishna Balaram Temple)",
    type: "temple",
    location: { city: "Vrindavan", state: "Uttar Pradesh", country: "India" },
    primaryFigure: "Lord Krishna & Balarama / A.C. Bhaktivedanta Swami Prabhupada",
    faith: "Hindu — Gaudiya Vaishnavism (Hare Krishna)",
    icon: "🦚",
    theme: { bg: "bg-orange-50", nav: "bg-orange-800", navText: "text-white", accent: "bg-orange-700", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-900" },
    description: "The main ISKCON temple in Vrindavan — the land of Krishna's childhood pastimes. Founded by Srila Prabhupada, whose samadhi is also here. The temple runs continuous kirtans and is a magnet for Western devotees and Indian Vaishnavas alike.",
    significance: "Vrindavan is said to be a spiritual realm that has descended to Earth. 5,000+ temples dot the town. Walking Vrindavan is said to be equal to many lifetimes of penance.",
    auspiciousDays: ["Janmashtami", "Radhashtami", "Ekadashi", "Holi (Phalguna)"],
    rituals: [
      { id: "abhishek-krishna", name: "Abhishek of Krishna Balaram", description: "Sacred bathing of the presiding deities", offerings: "Panchamrit, flowers, tulsi", duration: "1 hour", price: 40, includes: ["Abhishek in your name", "Video", "Tulsi prasad shipped"], livestream: false },
      { id: "naam-japa", name: "10,000 Naam Japa Dedication", description: "Priest chants the Hare Krishna Maha-Mantra 10,000 times for you", offerings: "null", duration: "2 hours", price: 30, includes: ["10,000 Hare Krishna japa in your name", "Video of chanting", "Tulsi mala shipped"], livestream: false },
    ],
    festivals: ["Janmashtami (grand celebration)", "Radhashtami", "Holi (Phalguna — unique here)", "Govardhan Puja"],
    diaspora: ["Hare Krishna devotees globally", "USA", "UK", "Russia", "Australia", "Brazil"],
    lifeProblems: ["Devotion", "Purification", "Relationship with God", "Spiritual community"],
    trustNotes: "Run by ISKCON (International Society for Krishna Consciousness)",
    tags: ["krishna", "hare-krishna", "vrindavan", "iskcon", "prabhupada", "vaishnavism"],
  },
  {
    slug: "ramakrishna-belur-math",
    id: "G004",
    name: "Belur Math (Ramakrishna Math & Mission HQ)",
    type: "samadhi",
    location: { city: "Belur", state: "West Bengal", country: "India" },
    primaryFigure: "Sri Ramakrishna Paramahamsa / Swami Vivekananda",
    faith: "Hindu — Vedanta (universal)",
    icon: "🙏",
    theme: { bg: "bg-orange-50", nav: "bg-orange-900", navText: "text-white", accent: "bg-orange-800", accentText: "text-white", badge: "bg-orange-100", badgeText: "text-orange-900" },
    description: "The headquarters of the Ramakrishna Math and Mission, established by Swami Vivekananda on the Ganges bank. The architecture integrates Hindu, Islamic, and Christian elements — a physical embodiment of 'All religions are true'. Sri Ramakrishna's holy relics are enshrined here.",
    significance: "Vivekananda said: 'Each soul is potentially divine.' Belur Math has been a center of universal Vedanta and humanitarian service for over 125 years.",
    auspiciousDays: ["Ramakrishna Jayanti (Feb/Mar)", "Vivekananda Jayanti (Jan 12)", "Durga Puja"],
    rituals: [
      { id: "puja-dedication", name: "Special Puja Dedication", description: "Puja at Sri Ramakrishna's shrine in your name", offerings: "Flowers, incense", duration: "1 day", price: 25, includes: ["Puja at the main shrine", "Video", "Prasad shipped"], livestream: false },
    ],
    festivals: ["Ramakrishna Jayanti", "Vivekandanda Jayanti", "Durga Puja (grand celebration)", "Kali Puja"],
    diaspora: ["USA", "UK", "Germany", "Global Vedanta followers"],
    lifeProblems: ["Universal spirituality", "Service (karma yoga)", "Philosophical inquiry", "Harmony of religions"],
    trustNotes: "Managed by Ramakrishna Math and Ramakrishna Mission (registered trust)",
    tags: ["ramakrishna", "vivekananda", "vedanta", "universal", "west-bengal"],
  },
]
